### ISSUE TITLE
Rails 7.1 deprecation warning

### ISSUE THREAD

**Issue by cedvw** [sunspot/sunspot#1039]
With Rails 7.1, Sunspot triggers a lot of deprecation warnings in the logs, e.g:

```
DEPRECATION WARNING: BOLD is deprecated! Use MODES[:bold] instead. (called from block (3 levels) in <top (required)> at [...])
DEPRECATION WARNING: Bolding log text with a positional boolean is deprecated and will be removed in Rails 7.2. Use an option hash instead (eg. `color("my text", :red, bold: true)`)
```

This is a low hanging fruit, and Mark Young already submitted a pull request with the fix two week ago: https://github.com/sunspot/sunspot/pull/1038

Would be nice to get that merged and released.

Thanks!

**Comment by serggl** [comment]
fixed with #1038
