### ISSUE TITLE
Discussion: Is this project dead? (aka: is this now abandonware?)

### ISSUE THREAD

**Issue by ryders** [sunspot/sunspot#1043]
Folks - I've been using this gem for a few years now... only with some small problems, but seriously **growing concerns**. Before hitting 1000 forks, I think something needs to be done here...

5 years ago it was acceptable that the gem was not "regularly updated" but now 5 years later, with very few updates since, I fear the core team might have moved on to other things? Thanks to the initial work that went into this. I think it's time to say this project is dead (although seems to be _the reference_ when it comes to interacting with solr with many rails project!)

With 145 issues opened, and most responses/comments are "oh me too" or "yes, that would be great", it's pretty clear this gem is solid (few bugs), but also getting old and dusty..

## `sunspot_rails` has served us all well
There's currently over 900 forks, several with updates and issues resolved / PRs merged. I would like to suggest pulling a few ppl together in order to move forward with a single fork and publish an alternative, with some degree of activity.

(I'm hoping project owners will respond and contribute their thoughts to this, but it's possible they don't. @serggl @outoftime @rywall @alindeman @njakobsen @bragboy)

> is this now a joke?

Please don't take this as passive-agressive or otherwise negative. I need everyone's attention now, because Ruby/Rails is a serious platform, Solr is a serious platform, and this project seems to be lacking any momentum. So I appreciate your work in getting this gem out and _maintaining it_ for several years, thank you. I also understand priorities change, you're all 10+years older now. 🤣

Now; I'm in a lucky position: I'm ok to consider changing our search index to elastic or else ([interesting read](https://dattell.com/data-architecture-blog/solr-vs-elasticsearch/)) but I would prefer to stand behind solr (and rails). However I lack knowledge (gem packaging, ci testing, solr inner working) to take this on by myself, but keen learn and work with others to move forward. 

## Effort going nowhere
Wow: https://github.com/sunspot/sunspot/pulls

There are several issues discussed (noting: very few responses by the gem core team), and PR raised/reviewed approved and yet releases do not happen, and just .... die off, wasting everyone's time in the process. 10/21 PRs go back 5+ years, so clearly there's no "project management" is happening here, further contributing to wasting contributions. 454 pull requests closed, only 26 [were actually merged](https://github.com/sunspot/sunspot/pulls?q=is%3Apr+is%3Aclosed+review%3Aapproved+is%3Amerged) 🤔

I mean... how is this PR still open? https://github.com/sunspot/sunspot/pull/535/files 
I mean... how is this not closed? https://github.com/sunspot/sunspot/issues/1021

I'm wtf: Throw exception on index unpersisted object #535

## Searching for contributors of value (imho)
There are individuals who have clearly spent significant time inside and around the gem/project. I'm listing a few for the purpose of tagging them. I can also see some "area of interest / skills" shaping up which could be interesting for a future team structure. **This is not an exhaustive list.** My apologies if I left you out, or didn't fully track your contribs - but please let yourself known!

Contributor | Input received | Other notes
--- | --- | ---
@mark-young-atg [fork](https://github.com/mark-young-atg/sunspot) | #1039 | doesn't seem very active on GH, very rails-centric based on forks
@s4na [fork](https://github.com/s4na/sunspot) | #1042 | several commits 12+ mths ago, and more recently with ruby-3.3 and others, very active on GH, possibly the none-core contributors having the most merged PRs 🤣
@gblair [fork](https://github.com/gblair/sunspot), with @negipo [repo](https://github.com/negipo/sunspot) | #1034, #1023 | not super active on GH, clear intention to help with different issues/discussions/contribs
@mlh758 | none addressed specifically, but commented to and tagged a number of issues up to about 2019 and later, also suggested #954 which I would agree with | otherwise fairly active on GH, could help split sunspot_rails and sunspot_solr, might have been previous core member? has [merged to master](https://github.com/sunspot/sunspot/pull/991).
@rocket-turtle [fork](https://github.com/rocket-turtle/sunspot) | #1018 | not super active, 
@gr8bit & @BlazingRockStorm | significant work on #993 | BlazingRockStorm might be able to help with repo/actions/ci?

## Issues to address
Irrespective of features requests, I think there needs to be some effort towards bringing the gem up-to-date (or close to) with latest ruby/rails/solr versions. I've pulled out the following issues;

Solr 8(.6) based update - we should totally merge this soon #993 (has had significant work done)
Rails 7.1 deprecation warning #1039
Update sunspot to Solr 7+? #989
Is this available with Solr 9? #1037
NoMethodError on Ruby 3.2 for File.exists? #1024
DEPRECATION: Rsolr.new/connect option 'read_timeout' is deprecated and will be removed in Rsolr 3. #1018
Remove/Deprecate sunspot_solr #954

I'm not sure this is a confirmed problem, but seems version/deprecation related:
Allow aliases when loading Rails yaml config #1041
Use YAML.unsafe_load to allow alias in configuration #1023
Psych::BadAlias in Ruby 3.1 configuration #1022

## My wishlist
Finally, I have not raised/documented this request, but I really need to store/query json/nested documents (not just numbers, strings and text) using this gem. In 2024 it's a problem not being able to deal with a full document indexing ([SOLR supports this](https://solr.apache.org/guide/solr/latest/indexing-guide/transforming-and-indexing-custom-json.html)).

## Proposal
* now: wait a 4-6 weeks to see get input (positive/negative) from anyone tagged in this post, or anyone else interested
* soon: form a new core team, hello, fork repo and take across a few issues and several PRs + assign todo
* later: publish new gem with a monthly/quarterly release cycle 
* nice to have: better document docker/solr-cloud/k8s setups for development/production

I'm also happy to contribute in time or otherwise (🍺 ☕️ 💰 😮), perhaps coordinate and just push things along.

Your thoughts?

**Comment by BlazingRockStorm** [comment]
Sorry, I moved from Sunspot to Searchkick with Elasticsearch/Opensearch. Love using Solr of it's lightweight, but I don't see any update on Sunspot

**Comment by serggl** [comment]
As a past contributor and maintainer of this project I have few things to say here.
I don't think forking this repo is a good way to go - the fork repo will face exactly the same problems you mentioned above.
The core problem here is lack of experienced devs using this project and willing to contribute. What's the plan on finding those for the fork? Why aren't they already contributing into this repo?

Unfortunately, I'm not dealing with Solr for a few years already, so I miss a lot of new context here. I think other past maintainers are also being silent because of this.
But I can say for sure, if you really want to push your changes to open source, you need to push for it (like I did here https://github.com/sunspot/sunspot/pull/826). 
Perhaps introducing a PR template to tag people for a review would fix the problem of stale PRs. Happy to help with this if other maintainers think it's a good idea.

**Comment by njakobsen** [comment]
As a past contributor and maintainer, I think the project needs to be maintained by people who are actively using it or it becomes a chore rather than a project. When @rywall and I could not continue as active maintainers we passed it on. Given that there are so many contributions, but nobody reviewing and merging, perhaps what the project needs is a person like you to, as you say, "coordinate and push things along." It sounds like you're using it actively and are invested in its future. Would you consider taking up the mantle?

**Comment by ryders** [comment]
Hi folks, I hope you all had a great summer.

@serggl thank you for making a release for a number of issues I pointed out as actioned.

@njakobsen I agree with you that active users should be maintaining this gem. While we are using it, several features in solr 9.5 are desirable to us and are not available through the gem. I have a limited knowledge of SOLR and the gem but can hack my way around many things, time permitted. 

I was hoping to gather a few ppl using the gem so that we could work at it together, but it's clear I cannot take this on by myself. Not sure whether there's a distribution list to call out for help and get a few ppl together? 

I'm considering a move over to Searchkick with ElasticSearch much like @BlazingRockStorm if we don't get a quorum in the coming 8-12 weeks.

**Comment by mlh758** [comment]
I was actively using Solr a couple of companies ago and so was more able to contribute here. My current job uses Elasticsearch so I'm not currently using/testing anything with Solr which is why I've gone dark here.
