### ISSUE TITLE
`solr_search` search modular models is not accurate

### ISSUE THREAD

**Issue by hsw15192617273** [sunspot/sunspot#1045]
- sunspot 2.6.0
- sunspot_rails 2.6.0
- rails 7.0.8
- solr 9.4.0

I defined two modular models. and declare searchable
```ruby
module Info
  class Bid < ApplicationRecord
  end
end

module Info
  class Firm < ApplicationRecord
  end
end
```

when i search `Info::Bid`, it's ok
```log
irb(main):005> Info::Bid.solr_search { with(:province_id, 1007); paginate(page: 1, per_page: 1) }.results.first
D, [2024-06-14T18:07:56.484262 #594] DEBUG -- :   SOLR Request (9.5ms)  [ path=select parameters={fq: ["type:Info::Bid", "province_id_i:1007"], start: 0, rows: 1, q: "*:*"} ]
  Info::Bid Load (2.5ms)  SELECT "info_bids".* FROM "info_bids" WHERE "info_bids"."id" = $1  [["id", 173290]]
=>
#<Info::Bid:0x00007fe92340a790
```

but if i search `Info::Firm`, it's returned `Info::Bid` record
```log
irb(main):006> Info::Firm.solr_search { with(:province_id, 1007); paginate(page: 1, per_page: 1) }.results.first
D, [2024-06-14T18:09:01.564125 #594] DEBUG -- :   SOLR Request (35.7ms)  [ path=select parameters={fq: ["type:Info::Firm", "province_id_i:1007"], start: 0, rows: 1, q: "*:*"} ]
  Info::Bid Load (2.3ms)  SELECT "info_bids".* FROM "info_bids" WHERE "info_bids"."id" = $1  [["id", 173290]]
=>
#<Info::Bid:0x00007fe920fb6ec0
```

I suspect the issue is due to incorrect handling of the type field value, leading to inaccurate search results. In the modular model, the type field contains two colons.

I believe the colons prevent a complete match during the search, which is why searching for `Info::Firm` results in retrieving data for `Info::Bid`.

right search:
![Xnip2024-06-14_17-06-01](https://github.com/sunspot/sunspot/assets/77371957/c087f92b-db06-4d7e-99a1-b018bac44b20)

wrong search:
![Xnip2024-06-14_17-05-17](https://github.com/sunspot/sunspot/assets/77371957/5ee8cb3d-6c6e-46a9-935b-2a768cdff18c)

So if i add `to_solr_conditional` method in `TypeField`, it worked
```ruby
module Sunspot
  # MONKEY PATCH
  class TypeField
    # MONKEY PATCH
    def to_solr_conditional(value)
      "\"#{value}\""
    end
  end
end
```

**Comment by serggl** [comment]
@hsw15192617273 this seems to be a reasonable patch. Would you volunteer to make a PR?

**Comment by hsw15192617273** [comment]
@serggl #1046 PR for this
