### ISSUE TITLE
Sunspot should have better support for Resque and other queues

### ISSUE THREAD

**Issue by nz** [sunspot/sunspot#105]
See gist for queueing resque jobs in ActiveRecord objects: https://gist.github.com/1282013
1. Create jobs for Resque: `Sunspot::Resque::Update` and `Sunspot::Resque::Remove`.
2. Support a `:resque` option on `searchable` which sets `auto_index: false, auto_remove: false` and mixes in the Resque `after_commit` and `before_destroy` hooks.

This could feed its way into a more generic approach to how the index and remove calls are invoked. We could use generic `after_commit` and `before_destroy` hooks to invoke Resque, DelayedJob, or synchronous calls, based on our sensible defaults and the user's preferences.

**Comment by mlh758** [comment]
Closing this due to age. Also, this is far enough outside the usual workflow that I would be uneasy bringing it into the main library.
