### ISSUE TITLE
This task has been moved to the sunspot_solr gem. To install, start and...

### ISSUE THREAD

**Issue by rvwong** [sunspot/sunspot#156]
Gentlemen, I hope you can help.  I've been using this wonderful sunspot_rails, sunspot_solr gem for about 3 months now.  Recently it stopped worked mysteriously.  I'm running it on a Windows 7 platform.  The only things I changed, was some unrelated gems related to sorcery an authentication gem, at least so I thought, when I attempt to start the solr search engine like I normally do by entering,
'rake sunspot:solr:run' I get the following error:

 Note: This task has been moved to the sunspot_solr gem. To install, start and
 stop a local Solr instance, please add sunspot_solr to your Gemfile:

 group :development do
   gem 'sunspot_solr'
 end

now I've never gotten this message before, my gemfile has the following:

gem 'sunspot_rails'
gem 'sunspot_solr'

my Rakefile has the entry:

require 'sunspot/rails/tasks'

Again this was working before, and now it isn't to be certain, I uninstalled all things related to solr and sunspot that I might have accumulated through various experimentations and followed the directions here and on sunspot_rails and ONLY put the following in my Gemfile.

gem 'sunspot'
gem 'sunspot_rails'
# This is an optional packaged Solr:

group :test, :development do
  gem 'sunspot_solr'
end

I ran bundle install, even bundle update to be sure.  I noticed the following gems were installed as a result
sunspot (1.3.0)
sunspot_rails (1.3.0)
sunspot_solr (1.3.0)

I should point out I have rsolr (1.0.6 ) installed as well

But when I type that command, I still keep getting that error message, I'm stumped can anyone shed some light on this??

Thank you...

**Comment by adrianoresende** [comment]
It works for me too, but should not be within the development group as standard?
Nothing changes if I get out of the group?
