### ISSUE TITLE
Autocommit by default?

### ISSUE THREAD

**Issue by icambron** [sunspot/sunspot#222]
I noticed that `sunspot_solr` doesn't autocommit by default. That's a tad confusing, since it seems to be best practice to configure it that way (e.g. https://gist.github.com/1282013#gistcomment-90842). It also leads to plugins that use `Sunspot.index!` by default (e.g. https://github.com/TV4/sunspot_mongoid/blob/master/lib/sunspot/mongoid.rb#L73). Is there a reason it's configured that way? Would you accept a pull request changing it?

**Comment by bikeath1337** [comment]
This was implemented a while ago...cleaning up.
