### ISSUE TITLE
Dynamic field names should not contain : - bad solr practice

### ISSUE THREAD

**Issue by ni-ka** [sunspot/sunspot#229]
Currently : are used in dynamic field names. However, in boost function queries those cannot be used.

According to a reply on the solr user list:

> Quoting from the new trunk example schema:
> 
> "field names should consist of alphanumeric or underscore characters only and
>     not start with a digit.  This is not currently strictly enforced,
>     but other field names will not have first class support from all components
>     and back compatibility is not guaranteed." 

underscores should be used instead.

**Comment by jeffgran** [comment]
:+1: This is still an issue.

**Comment by ethirajsrinivasan** [comment]
Please use the latest version of Sunspot.If the issue persists provide more information on it.
