### ISSUE TITLE
Rails 3.2.6, ActiveRecord::Relation, StubSessionProxy and =~

### ISSUE THREAD

**Issue by fredericlemaytw** [sunspot/sunspot#247]
Since the new rails update (3.2.6), there is a bug if there is a spec testings ActiveRecord::Relation object with =~.

Assumptions
- User has a searchable class method
- users is an ActiveRecord::Relation
- spec_helper uses `Sunspot.session = Sunspot::Rails::StubSessionProxy.new($original_sunspot_session)`

It will fail if I do:
`users.should =~ [ user_1, user_2 ]`

```
undefined method `config' for #<Sunspot::Rails::StubSessionProxy:0x007fcd8d3438e0>
     # /Users/flemay/.rvm/gems/ruby-1.9.3-p0@project/bundler/gems/sunspot-a253beddbeb8/sunspot/lib/sunspot.rb:545:in `config'
     # /Users/flemay/.rvm/gems/ruby-1.9.3-p0@project/bundler/gems/sunspot-a253beddbeb8/sunspot_rails/lib/sunspot/rails/searchable.rb:241:in `solr_index'
     # /Users/flemay/.rvm/gems/ruby-1.9.3-p0@project/gems/activerecord-3.2.6/lib/active_record/relation/delegation.rb:37:in `block in method_missing'
...
```

The test passes in the following cases:
- I remove that searchable method
- I do `users.to_a.should =~`

I think there is a link with that change: https://github.com/rails/rails/commit/cd1be1acc68221fbdfab0d13211d40bdeae630dc

**Comment by rohanpujaris** [comment]
Hi,

I am facing similar issue. Is this issue fixed in sunspot 2.2.3. And also is sunspot 2.2.3 good to go with rails 4.2.5.

**Comment by wtfiwtz** [comment]
Sunspot 2.1.1 works okay with Rails 4.2.5... I would imagine 2.2.3 should be the same :)... I had to keep on rsolr 1.0.9 though for this reason:

  # RSolr::Error::Http - 400 Bad Request
  # Error: Illegal character ((CTRL-CHAR, code 3))
  # at [row,col {unknown-source}]: [765,1]

**Comment by wtfiwtz** [comment]
See also https://github.com/sunspot/sunspot/pull/411

Here is my Sunspot initializer (sadly we are still on Solr 1.x)


[sunspot.rb.txt](https://github.com/sunspot/sunspot/files/82129/sunspot.rb.txt)

**Comment by rohanpujaris** [comment]
I checked #411, but worried to use it as Travis CI are failing and its not yet merged and last comment on PR was on Aug 16, 2013. But i think there is no other choice. Will check initializer provided by you. Thanks @wtfiwtz
