### ISSUE TITLE
NoMethodError (undefined method `result=' for nil:NilClass)

### ISSUE THREAD

**Issue by vncgregorio** [sunspot/sunspot#281]
I have a problem related to the use of sunspot solr. I have an application that performs some searches using this gem. There are 5 models that has this feature, 4 of them works great (really nice), only 1 of them is showing an error -_-'

    @search.results

    NoMethodError (undefined method `result=' for nil:NilClass):
       app/controllers/financial_dashboards_controller.rb:27:in `index'

Here is my code:

Controller

    @search = Sunspot.search(Purchase) do
       fulltext params[:search]
       with(:product_owner).equal_to(current_user.id)
       facet(:status)
       if params[:status].present?
          with(:status).equal_to(params[:status]) 
       end
       facet(:sell_date)
       if params[:sell_date].present?
          with(:sell_date).equal_to(params[:sell_date])
       end
       order_by(:sell_date, :desc)
    end

    #line 27
    @sales = @search.results.paginate(:page => params[:page], :per_page => 5)

Model (Purchase):

    searchable do
      text :product_name
      text :product_short_description
      integer :product_owner
      string :status
      string :sell_date
    end         

    def product_name
      product.name
    end

    def product_short_description
      product.short_description
    end

    def product_owner
      product.user.id
    end

    def sell_date
      date.to_s(:year_month)
    end

    #indicates status of the payment and delivery
    def status()
        if !self.closed.nil?
          I18n.t('purchases.status.finished')
        elsif !self.measured.nil?
          I18n.t('purchases.status.measured')
        elsif !self.accomplished.nil?
          I18n.t('purchases.status.delivered')
        elsif !self.paid.nil?
          I18n.t('purchases.status.paid')
        elsif !self.canceled.nil?
          I18n.t('purchases.status.canceled')
        elsif !self.date.nil?
          I18n.t('purchases.status.waiting_payment')
        end
    end

Another strange thing is that on my development machine, this code works perfectly. On production machine that uses nginx, the code displays this error.

I checked the version of gems and they match. I tried 
```
rake sunspot:solr:reindex RAILS_ENV=production
```

to reindex. I tried
```
rake sunspot:solr:stop RAILS_ENV=production
```
```
rake sunspot:solr:start RAILS_ENV=production
```

to restart the search server. Even tried to remove solr/ folder and let the start script copy it again. 

And why the other models work perfectly? Any ideas how to solve this?

Thanks

**Comment by darwayne** [comment]
For anyone coming from google, this error occurs when you don't have a unique primary key on your model.

**Comment by bragboy** [comment]
Closing this issue. If this still persist in the newer versions of the gem, feel free to reopen.
