### ISSUE TITLE
Sunspot Reindex appears to run twice

### ISSUE THREAD

**Issue by nik-efimov-yyz** [sunspot/sunspot#311]
Whenever I call rake sunspot:reindex, it appears that it indexes twice.

The progress bar reaches the end, then restarts at zero and does it all over again, with identical data shown (same number of docs, pretty much the same time to process).

Is that normal?

**Comment by JackGalore** [comment]
I am also seeing this happen with version `2.2.6`. Has anyone found a cause and/or solution?

**Comment by adamhooper** [comment]
I had the same problem and solved it.

Remove this from your Rakefile: `require 'sunspot/rails/tasks'`. It's cruft, and it makes every task run twice.
