### ISSUE TITLE
not possible to chain searches or perform a subsearch / refinement of the main search's results

### ISSUE THREAD

**Issue by mladeny** [sunspot/sunspot#330]
I looked through the documentation and did not see the ability to perform a second search based on the first one.
For example, I have a search that retrieves a number of objects

```
@authors_articles = Sunspot.search(Article) do |search|
  search.with(:is_published, true)
  search.with(:author_id, 5)
```

once I have all of the author's articles, I want to get only the ones that are featured, so I want to perform a second search on the first search's results

```
@authors_featured_articles = @authors_articles.search do
  with(:is_featured, true)
```

@authors_featured_articles will contain the results of @authors_articles that have :is_featured set to true

Right now I'm basically performing 2 searches to get both results, which is really not efficient, since the second search is a subsearch/refinement of the first one.

**Comment by ethirajsrinivasan** [comment]
Please make use of the helper
