### ISSUE TITLE
sunspot installation for rails 2.3.11 app

### ISSUE THREAD

**Issue by santoshbt** [sunspot/sunspot#348]
I am trying to install sunspot for rails 2.3.11 app, and not getting the proper results. While I am doing the "rake sunspot:solr:start", it always throw me the error  
 Note: This task has been moved to the sunspot_solr gem. To install, start and
  stop a local Solr instance, please add sunspot_solr to your Gemfile:

  group :development do
    gem 'sunspot_solr'
  end

and nothing happens. So I installed bundler gem, which generated gemfile. Added 'sunspot_solr' in it. But when I run  "rake sunspot:solr:start", it throws the same error, without any luck. So is it possible to install sunspot in rails 2.3.x version or is it mandatory to upgrade it to rails 3 version?

**Comment by adrianoresende** [comment]
I have this error too.
```gem 'sunspot_rails', '2.2.0'
group :development do
    gem 'sunspot_solr', '2.2.0'
end
