### ISSUE TITLE
Some Tutorials/Articles links in the README are dead :(

### ISSUE THREAD

**Issue by carols10cents** [sunspot/sunspot#384]
These links are outdated; I'm not sure if there are different URLs that could be used or if these resources are gone:

* How to Implement Spatial Search with Sunspot and Solr (Code Quest) http://codequest.eu/articles/how-to-implement-spatial-search-with-sunspot-and-solr
* rails3 + heroku + sunspot : madness (anhaminha) http://anhaminha.tumblr.com/post/632682537/rails3-heroku-sunspot-madness
* Full text search with Sunspot in Rails (hemju) http://hemju.com/2011/01/04/full-text-search-with-sunspot-in-rail/
* Chef recipe for Sunspot in production https://gist.github.com/336403
* How To Use Twitter Lists to Determine Influence (Untitled Startup) http://www.untitledstartup.com/2010/01/how-to-use-twitter-lists-to-determine-influence/
* Sunspot Quickstart (WebSolr) http://wiki.websolr.com/index.php/Sunspot_Quickstart
* The Saga of the Switch (mrb -- includes comparison of Sunspot and Ultrasphinx) http://michaelrbernste.in/2010/04/08/the-saga-of-the-switch.html

**Comment by bragboy** [comment]
https://github.com/sunspot/sunspot/pull/733 removed the dead links as on that date. Will have to keep monitoring them.
