### ISSUE TITLE
Connection refused URL:http://localhost:8982/solr/default/update

### ISSUE THREAD

**Issue by g8d3** [sunspot/sunspot#442]
Gemfile:

```
gem 'sunspot_solr', github: 'sunspot/sunspot', branch: 'master'
gem 'sunspot_rails', github: 'sunspot/sunspot', branch: 'master'
```

This is the output of `rake sunspot:solr:reindex`:

```
Connection refused - {:data=>
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:Service</query></delete>",
 :headers=>{"Content-Type"=>"text/xml"}, :method=>:post,
 :params=>{:wt=>:ruby}, :query=>"wt=ruby", :path=>"update",
 :uri=>#<URI::HTTP:0x007ffb7305d978 URL:http://localhost:8982/solr/default/update?wt=ruby>,
 :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil,
 :retry_after_limit=>nil}
```

I can access admin console at `http://localhost:8982/solr/`

`tail -f -n 99 log/sunspot-solr-development.log` does not change, seems request is going to other URL.

**Comment by rioX41** [comment]
I have same problem and I just resolved it by installing solr on my ubuntu, please take a look at this :
[https://www.digitalocean.com/community/tutorials/how-to-install-solr-on-ubuntu-14-04](url)
