### ISSUE TITLE
Using multiple production solr servers in sunspot.yml

### ISSUE THREAD

**Issue by navied** [sunspot/sunspot#498]
Is there a way to specify which solr server to use for a specific model in the searchable?

**Comment by mlh758** [comment]
You could probably change the session out at runtime using the methods here: https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot.rb#L582

You would have to build a new session and swap it in. This could be tricky in a threaded environment though so you might want to wrap such an operation in a mutex.
