### ISSUE TITLE
Sunspot_rails installation problem in production - database configuration does not specify adapter

### ISSUE THREAD

**Issue by krishnasahoo** [sunspot/sunspot#500]
I am trying to install sunspot_rails in production environment.

run the following command in command prompt

```
rails g sunspot_rails:install
```

It gave me the following errors

```
/home/ec2-user/.rvm/gems/ruby-1.9.3-p448@xxx/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_specification.rb:47:in `resolve_hash_connection': database configuration does not specify adapter (ActiveRecord::AdapterNotSpecified)
```

I also tried to run it with mentioning rails environment as such

```
rails g sunspot_rails:install RAILS_ENV=production
```

It also give me the same error

When I run my application in production environment, everything comes fine except the page that refers sunspot solr search
That means the `database.yml` is fine

Next step I tried to install sunspot_solr using `sunspot_solr` gem. It did not created a sunspot.yml in my config folder.

But it `install` and `start` and `reindex` successfully. But when I actually visit the page with sunspot solr search, it gave me the same error. 

I tried to manually put the sunspot.yml in my config. but no change.

> Note: We have two server instances. One for application server,
> another for solr. Application is installed in both the servers.

Versions are as such

```
Ruby (1.9.3)

rails (3.2.13)
sunspot (2.0.0)
sunspot_rails (2.0.0)
mysql (2.9.1)
mysql2 (0.3.13)
```

**Comment by mlh758** [comment]
You should not be using the sunspot_solr gem in production. A standalone Apache Solr instance should be deployed and your sunspot.yml should be pointing to that.

Closing this due to age though.
