### ISSUE TITLE
Sunspot SOLR returns empty results

### ISSUE THREAD

**Issue by hapiben** [sunspot/sunspot#508]
I'm using Sunspot for search and MongoDB as backend database.

```
gem 'sunspot_rails',  '= 2.0.0.pre.120417'
```

I'm trying to search for a model using session. In the console:

```
> Sunspot.session = Sunspot::Rails.build_session
> search = Sunspot.search(Model) do
*   paginate(:per_page => 1, :page => 1)
> end
```

However, the results return an empty array.

```
> search.results
=> []
```

But if I try the search on page 2:

```
> search = Sunspot.search(Model) do
*   paginate(:per_page => 1, :page => 2) # Page 2
> end
> search.results
=> [<Model>]
```

Re-indexing Solr didn't help. Any ideas why? Thank you.

**Comment by mlh758** [comment]
Closing this due to age. It would be worth checking the hits instead of the results though to see if perhaps Solr thinks there were results but they didn't match up with what is in your database.

Default scopes have caused this problem for me in the past.
