### ISSUE TITLE
missing record after saving to database when using sunspot

### ISSUE THREAD

**Issue by poc7667** [sunspot/sunspot#511]
I tried to add some business orders and update the customer's status.

Bus somehow, After doing above actions.

Then, I can not found the updated customer  from front-end(webpage view) anymore.

This case sometimes will occurs.

But if I go to `rails console`.I can get the `customer` record and the update-to-date `order` status.

If I want to find the customer from `webpage` I should run `
yes | bundle exec rake sunspot:reindex
`
to reindex the solr database?

I run my server in development mode.
and I use the `postgres` DB
Here is my GEM file

```
 61   * rails (3.2.13)
 79   * sunspot (2.0.0)
 80   * sunspot_rails (2.0.0)
 81   * sunspot_solr (2.0.0)
49   * pg (0.17.0)
```

Here is my SCHEM XML https://gist.github.com/poc7667/7728095

**Comment by mlh758** [comment]
Closing this due to age.
