### ISSUE TITLE
Errno::ECONNREFUSED with solr on tomcat

### ISSUE THREAD

**Issue by beviz** [sunspot/sunspot#515]
I have a tomcat server running solr, nonsked sunspot throw below error and linode will send me report "Your Linode has exceeded the notification threshold (1000) for disk io rate by averaging 1094.39 for the last 2 hours", then i must do `service tomcat6 restart`, it will get well.

```
Errno::ECONNREFUSED (Connection refused - {:data=>"fq=type%3AProduct&fq=publishing_b%3Atrue&fq=store_id_i%3A6&fq=shelf_ids_im%3A19&sort=score+desc&start=0&rows=40&q=%2A%3A%2A", :method=>:post, :params=>{:wt=>:ruby}, :query=>"wt=ruby", :headers=>{"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"}, :path=>"select", :uri=>#<URI::HTTP:0x00000007e988b8 URL:http://localhost:8983/solr/select?wt=ruby>, :open_timeout=>nil, :read_timeout=>nil, :retry_503=>nil, :retry_after_limit=>nil}):
```

Is it the problem about connection pool's configuration?

**Comment by mlh758** [comment]
Closing this due to age, and this looks more like a solr setup issue which is outside the scope of the gem.
