### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by carlaares** [sunspot/sunspot#519]
Im trying to use this gem with solr under HTTPS (with tomcat7).
Configuration file seems to not support ssl configuration. Also adding ENV['SOLR_URL'] with prefix https it does not use https.

**Comment by brevilo** [comment]
Are you using sunspot_rails? If so, then set `scheme` to `https` for the core in question in `sunspot.yml`.

**Comment by carlaares** [comment]
hi @brevilo , I'm not using solr anymore, we switch to elastic search, so I can't confirm if your solution works or not. Feel free to close this issue if I'm the only one that had this problem. Thanks

**Comment by brevilo** [comment]
Sorry, since I'm not affiliated with the project I can't close it.
