### ISSUE TITLE
Upgrade from Rails 3.2, sunspot_rails and sunspot_solr 1.3.3, to Rails 4.x and gems version 2.1.x

### ISSUE THREAD

**Issue by clod81** [sunspot/sunspot#527]
Hi,
I'm trying to upgrade my Rails app to rails v 4.x and therefore using gems v > 2.x .
I tried to use gems version 1.3.3, but it looks like they are not compatible with new rails version...

I now start solr in development and test doing: sunspot-solr start , leaving default options.

Anyway, I have most of the things working, apart from a strange behavior.

I have a model defined pretty much like this:

```
class AAA < ActiveRecord::Base

searchable do
    text    :code
    text    :name
end

end
```

Let's say I have a database entry with those values:

```
code: 'ABC'
name 'testy searchy'
```

If I try to do:

```
AAA.search do
   fulltext('abc')
end
```

I get proper result

If I try to do:

```
AAA.search do
   fulltext('ab')
end
```

I get proper result

If I try to do:

```
AAA.search do
   fulltext('testy')
end
```

I get proper result.

But if I try:

```
AAA.search do
   fulltext('tes')
end
```

I don't get any results, whereas in version 1.3.3 everything used to work fine.

What am I missing?

**Comment by mlh758** [comment]
Closing this due to age and this doesn't appear to still be an issue.
