### ISSUE TITLE
What Solr versions are supported by sunspot?

### ISSUE THREAD

**Issue by Goltergaul** [sunspot/sunspot#529]
I can't find information in this in the wiki. Which versions are supported by sunspot? The sunspot_rails gem shipps with solr 4.2. Does that mean i cannot use a newer solr version? I've seen some issues regarding solr 4.6. in the issues. so which is the newest supported version?

**Comment by mlh758** [comment]
I'm using Sunspot 2.2.7 and am able to use solr 6.6 without issue.

I am upgrading to solr 7.1 soon to mitigate a security issue pointed out in #899

So far the only issue I've encountered moving to 7 is that the syntax being used for index time boosting appears to be deprecated. I just moved the boost to the `search` block and it continues to work as expected.

**Comment by cec** [comment]
Hi @mlh758 ,

I opened #951 to collect experiences of people that upgraded from 5.5.5 already.

Could you please comment on #951 about issues you encountered when migrating 5.x => 6.6 => 7.1?

I'm trying to collect information in one single place to
- have a safe upgrade path for our own apps
- discuss with gem maintainers about upgrading the bundled SOLR

It would be great if you can share your experience.

Thanks :)

**Comment by mlh758** [comment]
Closing this since I think it was sufficiently answered.

The gem works well at least up to Solr 7.7.2 although you will have to make some changes to the default schema.xml.
