### ISSUE TITLE
sunspot:solr:start attempts to start solr twice

### ISSUE THREAD

**Issue by dgehrett** [sunspot/sunspot#562]
Having recently upgraded to sunspot-rails 2.1.0 and sunspot_solr 2.1.0, I've noticed the following when running ```rake sunspot:solr:start```

```zsh
vagrant@mcr-dev-box:/vagrant$ ps aux | grep "solr" | grep "development"
vagrant@mcr-dev-box:/vagrant$ rake sunspot:solr:start
syck has been removed, psych is used instead
Successfully started Solr ...
rake aborted!
Server is already running with PID 20741
/home/vagrant/.rvm/gems/ruby-2.0.0-p353/gems/sunspot_solr-2.1.0/lib/sunspot/solr/server.rb:62:in `start'
/home/vagrant/.rvm/gems/ruby-2.0.0-p353/gems/sunspot_solr-2.1.0/lib/sunspot/solr/tasks.rb:12:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => sunspot:solr:start
(See full trace by running task with --trace)
```

I've verified that I have no pre-existing solr processes running.

**Comment by hennevogel** [comment]
@dgehrett do you have a require in your own Rakefile for sunspot/solr/tasks?

**Comment by bragboy** [comment]
Feel free to reopen if this problem still persist in `2.2.0`

**Comment by mbhnyc** [comment]
A colleague is seeing this too on 2.2.0, and `rake sunspot:solr:run` starts just fine.  Other machines are able to run this just fine.

**Comment by nathanpaul** [comment]
I'm seeing this issue in 2.2.5. I'm using rsolr 1.1.1 if that's any help.
