### ISSUE TITLE
Sunspot Partial Updates

### ISSUE THREAD

**Issue by bpourriahi** [sunspot/sunspot#567]
I've learned that Sunspot does not support partial updates. Solr didn't in the past, but now does.

We have a lot of content in our application that we search over. A lot of this content is highly related to a lot of other content, so indexing them takes a while.

We have a tagging system for our content, and each document/content has a tag_ids field. This works fine for searching, but for updating, if a user adds a tag, in order to update the index properly, we have to go find all the content that should be tagged, and reindex all of that content from scratch. Currently it takes over 3 minutes every time a tag is added or removed to update the index.

I'm trying to find solutions to get around this. I've tried devising a strategy where we index the ContentTag as a document where each field has a TagID, ContentID, and ContentType. Doing it this way makes it hard to receive the content though since you have to search off of contentID and contentType which would require a boolean statement for every content.

Another possibility was to give each document a unique ID, and just store the unique ID along with the TagID. This would make it trivial to search, because you'd just have to find all the documents with the specified unique IDs (two searches).

The issue with this is with indexing. In order to do a full reindex, we have to obtain the unique document ID for each document from SOLR, which seems like too much work. If there was a simple way to index this information or obtain it from SOLR without doing a query on every document in SOLR, then this would work. But I haven't figured out how to do that or if it's possible.

I would really appreciate some suggestions in dealing with this issue. I would consider even writing some code to make Sunspot work with Solr's partial/atomic update mechanism.

Thank you.
- Bijan

**Comment by kristianm** [comment]
+1

**Comment by saidie** [comment]
+1

**Comment by sergey-verevkin** [comment]
+1

**Comment by serggl** [comment]
#738
Please be kind

**Comment by hammady** [comment]
I have this problem too.
