### ISSUE TITLE
gem 'sunspot_rails' in Gemfile pulls the outoftime/sunspot repo which appears to be out of date.

### ISSUE THREAD

**Issue by robertwbradford** [sunspot/sunspot#569]
I had just added `gem 'sunspot_rails'` and `gem 'sunspot_solr'` in my Gemfile of a Rails 4 app. I kept getting the following error:

```
DEPRECATION WARNING: You have required `active_support/core_ext/object/to_json`. This file will be removed in Rails 4.2. You should require `active_support/core_ext/object/json` instead. (called from <top (required)> at /.../config/application.rb:7)
```

When inspecting my local copy of the sunspot_rails gem I found this in `sunspot_rails/lib/sunspot_rails.rb`:

```
# This needs to be loaded before sunspot/search/paginated_collection
# or #to_json gets defined in Object breaking delegation to Array via
# method_missing
require 'active_support/core_ext/object/to_json'

require 'sunspot/rails'
require 'sunspot/rails/railtie'
```

It was confusing though because the `sunspot/sunspot` repo shows this in `sunspot_rails/lib/sunspot_rails.rb`:

```
# This needs to be loaded before sunspot/search/paginated_collection
# or #to_json gets defined in Object breaking delegation to Array via
# method_missing
if Rails::VERSION::MAJOR > 4 || (Rails::VERSION::MAJOR == 4 && Rails::VERSION::MINOR >= 1)
  require 'active_support/core_ext/object/json'
else
  require 'active_support/core_ext/object/to_json'
end

require 'sunspot/rails'
require 'sunspot/rails/railtie'
```

That's when I realized that including `gem 'sunspot_rails'` in my gem file pointed to the old `outoftime/sunspot` repo. (I added the `github: 'sunspot/sunspot'` option in the Gemfile, and it all worked fine.)

Does rubygems.org need to be updated to point to this repo, or am I missing something?

**Comment by mlh758** [comment]
Closing this since it should be fixed by taking a newer version that has the changes.
