### ISSUE TITLE
Sunspot Solr Reindexing failing due to illegal characters

### ISSUE THREAD

**Issue by jack-nie** [sunspot/sunspot#570]
I'm having an issue where Solr is failing to reindex my site, due to the following error from my production log:

bundle exec rake sunspot:solr:reindex
rake aborted!
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: Illegal character ((CTRL-CHAR, code 12))
 at [row,col {unknown-source}]: [155,1]
I am not sure where this 'illegal character' is being generated from, nor where to find this. I more than appreciate everyone's help, as it is causing a 500 server error on my app right now. Thank you, and let me know if more information is needed.

**Comment by bjones** [comment]
+1 to reopen; I can understand not wanting to slow down indexing for this filter if it doesn't apply to your data, but I also think it makes sense to provide at a minimum a simple hook mechanism to filter data if this is a problem for the data you have and cleaning the data source isn't necessarily an option.

**Comment by woodhull** [comment]
+1 to reopen. Is sunspot still maintained? Last commit was in August, tons of open PRs.

**Comment by jamesprior** [comment]
Looks like ruby 1.9 and up has a handy regex matcher for this too, see http://www.ruby-doc.org/core-1.9.3/Regexp.html for details.  In my limited testing

  `content.gsub!(/[[:cntrl:]]/,'')`

strips them out nicely

**Comment by bpourriahi** [comment]
It might be better to fix this at the schema level (solr) rather than at the sunspot level.

**Comment by brianjlandau** [comment]
@bpourriahi can you give an example of how one might do this? I'm currently using `HTMLStripCharFilterFactory` already. What other `charFilter` should I add and how would I configure it?

**Comment by hidde-jan** [comment]
I'm currently testing adding something like this to the schema:

```xml
<analyzer>
  <charFilter class="solr.PatternReplaceCharFilterFactory"
             pattern="[\u0000-\u001f]+" replacement=""/>
  or
  <charFilter class="solr.PatternReplaceCharFilterFactory"
             pattern="\\p{Cntrl}" replacement=""/>
  <tokenizer ...>
  [...]
</analyzer>
```
has anybody here got some more insight?

**Comment by rajiteh** [comment]
Ran in to the same issue, using the monkey patch provided by @beffa with a slight modification to support unicode char sets.

```ruby
# config/initializers/extensions/sunspot_strip_control_chars.rb
module Sunspot
  #
  # DataExtractors present an internal API for the indexer to use to extract
  # field values from models for indexing. They must implement the #value_for
  # method, which takes an object and returns the value extracted from it.
  #
  module DataExtractor #:nodoc: all
    #
    # AttributeExtractors extract data by simply calling a method on the block.
    #
    class AttributeExtractor
      def initialize(attribute_name)
        @attribute_name = attribute_name
      end

      def value_for(object)
        Filter.new( object.send(@attribute_name) ).value
      end
    end

    #
    # BlockExtractors extract data by evaluating a block in the context of the
    # object instance, or if the block takes an argument, by passing the object
    # as the argument to the block. Either way, the return value of the block is
    # the value returned by the extractor.
    #
    class BlockExtractor
      def initialize(&block)
        @block = block
      end

      def value_for(object)
        Filter.new( Util.instance_eval_or_call(object, &@block) ).value
      end
    end

    #
    # Constant data extractors simply return the same value for every object.
    #
    class Constant
      def initialize(value)
        @value = value
      end

      def value_for(object)
        Filter.new(@value).value
      end
    end

    #
    # A Filter to allow easy value cleaning
    #
    class Filter
      def initialize(value)
        @value = value
      end
      def value
        strip_control_characters @value
      end
      def strip_control_characters(value)
        return value unless value.is_a? String
        value.gsub(/[\0-\x1f\x7f\u2028]/,'')
      end
    end

  end
end
```

**Comment by hammady** [comment]
Please reopen.

**Comment by vickyonit** [comment]
+1

**Comment by CaseKey** [comment]
I also have this issue, but overwriting the Data Extractor doesn't solve it for me

**Comment by hammady** [comment]
@hidde-jan tried modifying the schema like your suggestion, but it still fails. I tried replacing ordinary characters to test the charFilter and it was ok. However, it throws 400 for many [patterns](http://www.regular-expressions.info/unicode.html#category) i was trying:
`[\u0000-\u001f]+`, `[\\u0000-\\u001f]+`, `[\p{C}]+`, `[\\p{C}]`.
Did you manage to get it working?
I am afraid Solr rejects the input before it even enters the filter chain.

**Comment by dwbutler** [comment]
Thanks @rajiteh, I copy-pasted your solution and it fixed the issue for me.

**Comment by toothrot** [comment]
@hammady @CaseKey @rajiteh you may want to try the following in place of the `gsub`:

```ruby
str.encode(str.encoding, "binary", invalid: :replace, undef: :replace)
```

See:
https://bibwild.wordpress.com/2013/03/12/removing-illegal-bytes-for-encoding-in-ruby-1-9-strings/
http://ruby-doc.org/core-2.0.0/String.html#method-i-encode

**Comment by toothrot** [comment]
Or, even better:

```ruby
str.scrub
```

http://ruby-doc.org/core-2.2.2/String.html#method-i-scrub

**Comment by mminute** [comment]
@rwc9u 's modified version of @beffa 's patch (posted Sep 9, 2014) solved this for me by adding capability to handled characters embedded in arrays or hashes.

**Comment by abhijitsinha** [comment]
@rwc9u yes I too wrote the same logic to get it to work with arrays.

**Comment by bestori** [comment]
+:1 for reopening 

(I'm with "Error: 'Illegal character ((CTRL-CHAR, code 11))")

**Comment by angelic** [comment]
+1 to reopen, also with "Error: 'Illegal character ((CTRL-CHAR, code 11))"

**Comment by angelic** [comment]
I managed to strip out the vertical tab that was giving me trouble (Ctrl Char 11) with the following monkeypatch based on previous comments. It works with Arrays and Hashes and gsubs any nonprintable characters that are not linebreaks or tabs (which Solr seems fine with).

```ruby
# config/initializers/sunspot_strip_control_chars.rb
module Sunspot
  #
  # DataExtractors present an internal API for the indexer to use to extract
  # field values from models for indexing. They must implement the #value_for
  # method, which takes an object and returns the value extracted from it.
  #
  module DataExtractor #:nodoc: all
    #
    # AttributeExtractors extract data by simply calling a method on the block.
    #
    class AttributeExtractor
      def initialize(attribute_name)
        @attribute_name = attribute_name
      end

      def value_for(object)
        Filter.new( object.send(@attribute_name) ).value
      end
    end

    #
    # BlockExtractors extract data by evaluating a block in the context of the
    # object instance, or if the block takes an argument, by passing the object
    # as the argument to the block. Either way, the return value of the block is
    # the value returned by the extractor.
    #
    class BlockExtractor
      def initialize(&block)
        @block = block
      end

      def value_for(object)
        Filter.new( Util.instance_eval_or_call(object, &@block) ).value
      end
    end

    #
    # Constant data extractors simply return the same value for every object.
    #
    class Constant
      def initialize(value)
        @value = value
      end

      def value_for(object)
        Filter.new(@value).value
      end
    end

    #
    # A Filter to allow easy value cleaning
    #
    class Filter
      def initialize(value)
        @value = value
      end

      def value
        if @value.is_a? String
          strip_control_characters_from_string @value
        elsif @value.is_a? Array
          @value.map { |v| strip_control_characters_from_string v }
        elsif @value.is_a? Hash
          @value.inject({}) do |hash, (k, v)|
            hash.merge( strip_control_characters_from_string(k) => strip_control_characters_from_string(v) )
          end
        else
          @value
        end
      end

      def strip_control_characters_from_string(value)
        return value unless value.is_a? String
        value.gsub /[^[:print:]\r\n\t]/, ''
      end
    end
  end
end
```

**Comment by Geesu** [comment]
+1 to reopen

**Comment by letsdothis-roguethink** [comment]
+1 to reopen

**Comment by bogdan8** [comment]
i am having this error,  maybe something had this error?
`"msg":"ERROR: [doc=Performer 109] Error adding field 'title_text'='Aerosmith' msg=For input string: \"Aerosmith\"",`

**Comment by heaven** [comment]
Regarding removing it at the Solr side, there is a pity behavior in versions > 5.3.1 –
https://issues.apache.org/jira/projects/SOLR/issues/SOLR-6468

In short – when removing words using stop filters the filter leaves gaps. So if you blacklist word `http` it will create the following tokens when indexing `http://twitter.com/username`:
* ?
* twitter
* com
* username

Search requests for `twitter.com/username` will fail, because `?` would be missing in the query.

**Comment by agibralter** [comment]
Is there a more official API to filter what is being sent to Solr?

**Comment by agibralter** [comment]
Also, a slightly more concise monkey patch:

```ruby
module SunspotDataExtractorMonkeyPatch
  def value_for(*args)
    Filter.new(super).stripped_value
  end

  class Filter
    def initialize(value)
      @value = value
    end

    def stripped_value
      if value.is_a?(String)
        strip_control_characters_from_string(value)
      elsif value.is_a?(Array)
        value.map { |v| strip_control_characters_from_string(v) }
      elsif value.is_a?(Hash)
        value.inject({}) do |hash, (k, v)|
          hash.merge( strip_control_characters_from_string(k) => strip_control_characters_from_string(v) )
        end
      else
        value
      end
    end

    private

    attr_reader :value

    def strip_control_characters_from_string(value)
      return value unless value.is_a?(String)
      value.gsub(/[^[:print:]]/, ' ')
    end
  end
end

Sunspot::DataExtractor::AttributeExtractor.prepend(SunspotDataExtractorMonkeyPatch)
Sunspot::DataExtractor::BlockExtractor.prepend(SunspotDataExtractorMonkeyPatch)
Sunspot::DataExtractor::Constant.prepend(SunspotDataExtractorMonkeyPatch)
```

**Comment by serggl** [comment]
is there a real need to patch Sunspot internals for this instead of cleaning `searchable` fields in your project?

**Comment by agibralter** [comment]
@serggl so, I feel pretty strongly that one should not be cleaning fields on the way into the database to support search functionality. What if you really need those characters? Perhaps that's a debate, but let's say we don't want to do that. So that leaves a few options. One is to filter in the `searchable` definition:

```ruby
searchable do
  text :title do
    title.gsub(/[^[:print:]]/, ' ')
  end
  text :body do
    body.gsub(/[^[:print:]]/, ' ')
  end
end

# or perhaps...
text :title { SolrFilterer.clean(title) }
```

This leads to a lot of duplication of code.

I'm not suggesting that Sunspot should be opinionated and should filter characters. Rather, it'd be nice if Sunspot provided a hook in it's configuration to filter values going into Solr. Perhaps something like:

```ruby
Sunspot.config.text_fitler = proc { |value| value.gsub(/[^[:print:]]/, ' ') }
```

Any thoughts?

**Comment by mlh758** [comment]
I'm not a fan of the monkey patch idea, or making a change to the standard library to support this. Different databases will have different requirements about what can be stored, and writing a cleaning function once that you use for your searchable blocks would reduce that code duplication substantially.

There also appears to be the option of using the filters with the analyzer in your schema.

**Comment by heaven** [comment]
There's a pull request for this https://github.com/sunspot/sunspot/pull/886 I just don't have enough time to add tests. If anyone willing to help this could be merged eventually.

**Comment by heaven** [comment]
@mlh758 there is no way to filter this out using filters in the schema because the request never reaches there failing due to XML transport limitations. Solr actually fine with all these characters.

**Comment by mlh758** [comment]
@heaven yeah I saw that on the other thread. Since solr itself is fine with these characters it does seem like something the library should address.

**Comment by mlh758** [comment]
Closing this since the PR was merged.
