### ISSUE TITLE
2.1.1 refuses to run on Windows

### ISSUE THREAD

**Issue by betam4x** [sunspot/sunspot#579]
> bundle exec rake sunspot:solr:run
This command is not supported on i386-mingw32. Use rake sunspot:solr:run to run Solr in the foreground.

2.1.0 worked fine.

**Comment by bendulum** [comment]
+1

**Comment by kathanboss** [comment]
When I pass in the version I want (2.1.0) and bundle, it just goes ahead and installs 2.1.1

Does anyone know why? Thanks!

**Comment by betam4x** [comment]
don't use ~>
