### ISSUE TITLE
Can't run development and test together.

### ISSUE THREAD

**Issue by ryanwilliams** [sunspot/sunspot#583]
I'm using Rails 4.0 and I start 2 instances of Solr, one for development, and one for running tests:

```
RAILS_ENV=development rake sunspot:solr:start
RAILS_ENV=test rake sunspot:solr:start
```

They run on different ports and have different data directories.

But now only the one that was hit first will work and the other will raise an exception:

```
RSolr::Error::Http - 404 Not Found Error
```

So as it stands it's impossible to do TDD because you can either run development OR tests, but never both together.

**Comment by rohandaxini** [comment]
Hi @ryanwilliams I am facing exactly the same issue, despite setting `data_path` AND `solr_home` I am having following errors.

RSolr::Error::Http: RSolr::Error::Http - 404 Not Found
Error:     Not Found 

I am not trying to run them together, but I am having basic issue of running sunspot and indexing the data itself. Recently I upgraded my sunspot 2.0.0 to the latest version. (Other gems I upgraded is rsolr and sunspot_rails)

My current gem versions are:-
sunspot (2.1.1)
rsolr (1.0.10)
sunspot_rails (2.1.1)

Any clues on how to fix this issue ?

**Comment by ryanwilliams** [comment]
I'm not sure what it could be but here's my sunspot config. If you recently upgraded Solr you should delete or move the old solr home and data and start fresh.

    development:
      solr:
        hostname: localhost
        port: 8982
        solr_home: solr_dev
        data_path: solr_dev/data
        log_level: INFO
        min_memory: 512M
        max_memory: 4G

    test:
      solr:
        hostname: localhost
        port: 8991
        solr_home: solr_test
        data_path: solr_test/data
        log_level: WARNING
        min_memory: 512M
        max_memory: 2G

**Comment by rohandaxini** [comment]
Thanks for your response @ryanwilliams 
Actually I did delete "solr" folder completely earlier too and again when you mentioned here. Then started a fresh, but then I get "400 Bad Request" error. I am unable to reindex data due to this error.

My config file
'
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    data_path: /solr/test
    solr_home: solr
'

Errors
'
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>2},'error'=>{'msg'=>'ERROR: [doc=Contact 1] unknown field \'asset_keyword_as\'','code'=>400}}
'

**Comment by rohandaxini** [comment]
And I don't have that field "asset_keyword_as" anywhere in my database.
