### ISSUE TITLE
Sunspot newb, joins

### ISSUE THREAD

**Issue by pedantix** [sunspot/sunspot#595]
So, I am not sure if Sunspot is the right tool for the following search scenario. 

I have active record tables as so.

```
State(:id, :name)
Group(:id, :name, :state_id,  :academic_year_id) 
AcademicYear(:id, :begins_on, :ends_on)#note begins on and ends on are Date fields
```

And I have made State searchable like so.

```
class State < ActiveRecord::Base
  searchable do
    text :name
    text :group_names do
        groups.map(&:name)
    end 
  end
end
```

I am very happy with the ability sunspot gives me to search text such as the name of a group and get the states associated with it. I would very much like to be able to constrain the results of states the academic years by a given mins and maxs. I would do this with an activerecord statement like 

```
State.joins(group: :academic_year).where( start is between min and max or end is between min and max) 
```

This is a far from perfect example however I am curious if there is some similar statement in Solr for constraining results

**Comment by mlh758** [comment]
The easiest thing to do would be indexing the related data directly on the model you will be searching.

You could also use a Solr [join](https://wiki.apache.org/solr/Join) but if you just need the couple of fields it might be easier to skip the join.
