### ISSUE TITLE
Weird Instance Variable Issue

### ISSUE THREAD

**Issue by betam4x** [sunspot/sunspot#603]
The following code works

```
search_term = params[:search][:term]

@results = Product.search do
   fulltext search_term
   paginate page: params[:page], per_page: 12
end
```

The following code does NOT work, returns every result in the index.

```
@search_term = params[:search][:term]

@results = Product.search do
   fulltext @search_term
   paginate page: params[:page], per_page: 12
end
```

Can anyone else reproduce this?  Rails 4.1.4, Sunspot Solr 2.1.0 (2.1.1 is bugged on Windows and doesn't work).

**Comment by mlh758** [comment]
Closing this due to age. I think this falls under more of a general Ruby scoping issue than an issue with Sunspot so I don't see a reason to explicitly call it out somewhere in documentation.
