### ISSUE TITLE
Reload operation

### ISSUE THREAD

**Issue by spalenza** [sunspot/sunspot#605]
Hello, 
I'm developing a dynamic synonyms. My application generate a synonyms.txt file and I need reload solr to my synonyms work. Sunspot supports solr reload operations like `Sunspot.commit`?

Thanks.

**Comment by ivar** [comment]
@rodolfospalenza Are you still working with synonyms in Sunspot? I see that Solr now has an API for programmatically updating synonyms.

see https://cwiki.apache.org/confluence/display/solr/Managed+Resources#ManagedResources-Synonyms

**Comment by rodolfospalenza** [comment]
Hi @ivar.
No but previously I used Solr reload action to update my synonyms.
First I update my synonyms file and after I reload solr.

Thanks for your help. :+1:

**Comment by mlh758** [comment]
Closing this due to age but I can reopen if this still needs support.
