### ISSUE TITLE
Getting all facets is not working (setting facet limit to -1)

### ISSUE THREAD

**Issue by IslamAzab** [sunspot/sunspot#627]
It is mentioned in the read me that setting facet.limit to -1 (any negative value actually) should return all facets. However that's not working.

> By default Sunspot will only return the first 100 facet values. You can increase this limit, or force it to
> return all facets by setting limit to -1.

**Comment by visitvinoth** [comment]
@IslamAzab , This works fine for me. Are you getting confused with results-limit and facet-limit?

For facet-limit, please ensure you use the following syntax.

`facet(:field_name, limit: -1)`
