### ISSUE TITLE
RSolr::Error::Http (RSolr::Error::Http - 500 Internal Server Error Error

### ISSUE THREAD

**Issue by nancy-luo** [sunspot/sunspot#639]
RSolr::Error::Http (RSolr::Error::Http - 500 Internal Server Error
Error:     {msg=SolrCore 'development' is not available due to init failure: Error opening new searcher,trace=org.apache.solr.common.SolrException: SolrCore 'development' is not available due to init failure: Error opening new searcher
    at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:1212)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:240)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:155)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1307)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:453)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:560)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382)

Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><add><doc><field name=\"id\">User 4</field><field name=\"type\">User</field><field name=\"type\">ActiveRecord::Base</field><field name=\"class_name\">User</field></doc></add>"

Backtrace: /home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/rsolr-1.0.10/lib/rsolr/client.rb:283:in `adapt_response'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/rsolr-1.0.10/lib/rsolr/client.rb:190:in`execute'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/rsolr-1.0.10/lib/rsolr/client.rb:176:in `send_and_receive'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/sunspot_rails-2.1.1/lib/sunspot/rails/solr_instrumentation.rb:16:in`block in send_and_receive_with_as_instrumentation'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/sunspot_rails-2.1.1/lib/sunspot/rails/solr_instrumentation.rb:15:in`send_and_receive_with_as_instrumentation'
(eval):2:in `post'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/rsolr-1.0.10/lib/rsolr/client.rb:82:in`update'
/home/cells/.rvm/gems/ruby-2.0.0-p481@rails403/gems/rsolr-1.0.10/lib/rsolr/client.rb:102:in `add'):
  rsolr (1.0.10) lib/rsolr/client.rb:283:in`adapt_response'
  rsolr (1.0.10) lib/rsolr/client.rb:190:in `execute'
  rsolr (1.0.10) lib/rsolr/client.rb:176:in`send_and_receive'
  sunspot_rails (2.1.1) lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in`block in instrument'
  activesupport (4.1.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.1.6) lib/active_support/notifications.rb:159:in`instrument'
  sunspot_rails (2.1.1) lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'
  (eval):2:in`post'
  rsolr (1.0.10) lib/rsolr/client.rb:82:in `update'
  rsolr (1.0.10) lib/rsolr/client.rb:102:in`add'
  sunspot (2.1.1) lib/sunspot/indexer.rb:107:in `add_documents'
  sunspot (2.1.1) lib/sunspot/indexer.rb:30:in`add'
  sunspot (2.1.1) lib/sunspot/session.rb:91:in `index'
  sunspot (2.1.1) lib/sunspot/session_proxy/abstract_session_proxy.rb:11:in`index'
  sunspot (2.1.1) lib/sunspot.rb:184:in `index'
  sunspot_rails (2.1.1) lib/sunspot/rails/searchable.rb:387:in`solr_index'
  sunspot_rails (2.1.1) lib/sunspot/rails/searchable.rb:487:in `perform_index_tasks'

what happened?

**Comment by ror-infobeans** [comment]
@nancy-luo , how did you solve this issue?

**Comment by martinbjeldbak** [comment]
For anyone also coming here from Google, I solved this by uninstalling the `java` homebrew package and instead installing java 8 with

```sh
brew cask install adoptopenjdk/openjdk/adoptopenjdk8
```

The issue seems to be related to the version of solr used in this gem not supporting the latest version of java (13 at the time of this writing).

Hope this help anyone out there!
