### ISSUE TITLE
Perform an OR between a scalar field and fulltext search?

### ISSUE THREAD

**Issue by niuage** [sunspot/sunspot#641]
```ruby
Book.search do
   any do
      fulltext "tupac"
      with :tags, ["southpark"]
   end
end
```

Since `any` accepts only fulltext, and `any_of` accepts only scalar fields, how do I find books with the word `tupac` OR tagged with `southpark`.

Thanks.

**Comment by ashlinchak** [comment]
Any changes?

**Comment by niuage** [comment]
Yes, use Elasticsearch.

**Comment by ashlinchak** [comment]
:) For me the quick solution was to add a text field :tags where I joined all tags.
