### ISSUE TITLE
Passing an empty array to any_of returns ALL records

### ISSUE THREAD

**Issue by groe** [sunspot/sunspot#657]
I use this code to search within a specific set of IDs.

```ruby
accessible_ids = current_user.accessible_foobars.pluck(:id)
Foobar.search do
  with(:id).any_of(accessible_ids)
end
```

When `accessible_ids` is an empty array the solr query is `id_s:[* TO *]` and returns ALL records, regardless of their ID.

I am using UUIDs and the model is configured as follows:
```ruby
searchable do
  string(:id)
#...
end
```

Is this a bug? In my case, before I added `unless accessible_ids.empty?` it allowed users to find results they should not have access to. If not handled I imagine this could be a security risk for many applications relying on `any_of` queries.

**Comment by maninalift** [comment]
This is interesting because I think the behaviour you want is more "correct", less likely to lead to surprises and 

Perhaps it would be good to add `any_of_strict` which returns nothing given an empty array,  or change the behaviour of `any_of` and provide another method for the current behaviour, perhaps `narrowed_by` might express the meaning of "matching any of these unless there are none of these in which case everything" more pithily.

**Comment by groe** [comment]
I can see the use case of filtering with the default setting being to display all results. However, it seems more logical to me in that case to remove the condition as a whole if the array is empty - like this:

```ruby
Foobar.search do
  with(:category).any_of(category_filter) unless category_filter.blank?
end
```

Whereas in my case working around the problem requires this:

```ruby
if accessible_ids.any?
  @results = (Foobar.search do
    with(:id).any_of(accessible_ids) 
  end)
else
  @results = []
end
```

**Comment by Martin91** [comment]
@groe  My solution is just to reset ids to `nil` and it works, because `nil` is a **nothing** meaning while an empty array is a **everything** meaning (pay attention to SOLR logs after each snippet):

```ruby
Event.search do
  with(:service_id, nil)
end.total      # => 0
# SOLR Request (3.7ms)  [ path=select parameters={fq: ["type:Event", "-service_id_i:[* TO *]"], start: 0, rows: 30, q: "*:*"} ]

Event.search do
  with(:service_id, [])
end.total      # => 398
# SOLR Request (5.7ms)  [ path=select parameters={fq: ["type:Event", "service_id_i:[* TO *]"], start: 0, rows: 30, q: "*:*"} ]
# 
```

So you can just change your code to:

```ruby
@results = Foobar.search do
  with(:id).any_of(accessible_ids.empty? ? nil : accessible_ids) 
end
```

**Comment by MajedBojan** [comment]
Hello Guys
i'm working in solr search in rails
i'm getting those units has all the array of amenities those i'm passing 
if i use any_of it will display all the units those has even one key from the array but i want only those units have all the array am passing
this my code
```
  with(:amenities).any_of([params[:amenities]]) if params[:amenities].present?
```
i changed to 

```
with(:amenities).all_of([params[:amenities]]) if params[:amenities].present?
```
but it's same

**Comment by Martin91** [comment]
@MajedBojan could you copy and paste solr request logs for both codes?
