### ISSUE TITLE
deprecration warnings in sunspot 2.1.1 when using rsolr 1.0.11

### ISSUE THREAD

**Issue by codeforkjeff** [sunspot/sunspot#661]
FYI, after upgrading to rsolr 1.0.11 (released just today), I get this deprecation warning when running `bundle exec rake sunspot:solr:reindex`

```
[DEPRECATION] `RSolr.escape` is deprecated (and incorrect).  Use `Rsolr.solr_escape` instead.
```

The following files call #escape which is made available through `include RSolr::Char` (which is deprecated as a whole; there's nothing else in that module):

sunspot/lib/sunspot/query/restriction.rb
sunspot/lib/sunspot/query/function_query.rb
sunspot/lib/sunspot/indexer.rb

I think the call can simply be replaced with Rsolr#solr_escape although these are 2 potential issues: 

1) they don't do the exact same escaping
2) it seems there is other/additional escaping going on in things like Sunspot::Query::Restriction::Base#solr_value, which should be checked against the Rsolr#solr_escape to avoid double escaping.

**Comment by sevenseacat** [comment]
just came to post this exact thing!

**Comment by DaniG2k** [comment]
+1

**Comment by reconstructions** [comment]
+1

**Comment by davidimoore** [comment]
+1

**Comment by codeforkjeff** [comment]
I've submitted a pull request. Note that I'm not at all an expert on Solr, so if you merge this before the Sunspot folks get a chance to review it, it's very much at your own risk!

**Comment by EhsanYousefi** [comment]
For now, just change rsolr version to 1.0.7 in Gemfile.lock and then run bundle!

**Comment by alecslupu** [comment]
I get the same Deprecation warning.

**Comment by nim1989** [comment]
Same here.

**Comment by benedictaluan** [comment]
Same here. +1

**Comment by IslamAzab** [comment]
+1

@EhsanYousefi Why would one revert to version 1.0.7 instead of 1.0.10 for example? The deprecation and change was not added till version 1.0.11 https://github.com/rsolr/rsolr/blob/master/CHANGES.txt

**Comment by EdwinRozario** [comment]
+1

**Comment by Valve** [comment]
We're halfway done removing sunspot from our project, partially because it seems like it's abandoned. I wonder how many +1s are needed for a maintainer to actually get up and do a grep rename escape to solr_escape.

**Comment by libitte** [comment]
+1

**Comment by mlettica** [comment]
+1

**Comment by codeforkjeff** [comment]
My PR has been merged into master (thank you @njakobsen), so closing out this issue.

**Comment by san983** [comment]
:+1:
