### ISSUE TITLE
Missing info on languages

### ISSUE THREAD

**Issue by hakunin** [sunspot/sunspot#664]
Hi,
I don't see any info on how to tell sunspot that I want to use langage X instead of english.

Thats kind of the first thing a non-english app needs after installing sunspot, so it seems like a candidate for readme/wiki page note.

Google is not helpful as well, so any official info on that would be awesome.

**Comment by bikeath1337** [comment]
@hakunin, would you like to create a PR with the suggested improvements?

**Comment by hakunin** [comment]
Sorry, no longer using it.
