### ISSUE TITLE
rake sunspot:solr:reindex going killed automatic

### ISSUE THREAD

**Issue by anuj-dhanju** [sunspot/sunspot#665]
Hi,
  when I am doing the reindex my product It's going automatic killed.
console logs:- 
xyz@li732-163:~/staging/xyg/current$ source $HOME/.rvm/scripts/rvm && RAILS_ENV=staging rake sunspot:reindex
Re-indexing Recommendation
Re-indexing Product
Killed
xyz@li732-163:~/staging/xyz/current$

**Comment by njakobsen** [comment]
This seems like a problem with your setup, though there's not really enough information in your post to diagnose it. You should post this issue on http://groups.google.com/group/ruby-sunspot or stackoverflow.com
