### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dwbutler** [sunspot/sunspot#666]
I need to use some of the new features in the master branch of the `sunspot` gem. Unfortunately, this gem hasn't had an official release to Rubygems in 10 months. I linked to the Github repository in my Gemfile, but this pulls in the whole git repository which weighs in at 60 MB! This caused our Heroku app to fail with `Compiled slug size: 359.7MB is too large (max is 300MB).`

It would be great if Sunspot could get regular releases so we can avoid vendoring in the gem or hosting a private gem server.

**Comment by nekogami** [comment]
Is there any reason why you can't fork the repository on master and then point the gemfile to your repository ? like:

gem 'sunspot_rails', :git => "git@github.com:CompanyName/sunspot.git", :branch => 'master'

beware though with the solr version for your dev env. If your use the one inside this gem you will have to update it (for cursor based search) like this

  git "git@github.com:CompanyName/sunspot.git", :branch => 'master' do
    gem 'sunspot_solr'
  end

**Comment by dwbutler** [comment]
As I mentioned, the repository weighs in at a whopping 60 MB, causing my Heroku app to run out of space. If I fork the repo, I will still have all the history and the repository size will be exactly the same.

I ended up vendoring the sunspot gem into my app.

**Comment by decasia** [comment]
@njakobsen @joneslee85 any thoughts on having a new release, or in general about the current state of project development? 

Currently it's a bit hard to figure out who the project maintainers are, and I see that there are a ton of open issues. This project is important to my organization and I'd be happy to commit some time to issue triage, test suite maintenance, etc, if that would be helpful.

**Comment by njakobsen** [comment]
@decasia @dwbutler A new release is doable for sure. Are there any pull requests that you'd like to see in the new release? Right now @rywall and myself are the most active project maintainers but have been busy with other projects. The project is in need of maintainers that have time to work through the backlog of pull requests and remove old code related to ruby 1.8.7.

**Comment by tylerjolmstead** [comment]
+1, I'd really appreciate a new release also. Waiting on #662 to be released, I can fork for now

**Comment by dwbutler** [comment]
@njakobsen Master has everything I need.

**Comment by njakobsen** [comment]
2.2.0 is out

**Comment by dwbutler** [comment]
:v:
