### ISSUE TITLE
Why is it not recommended to use sunspot_solr in production?

### ISSUE THREAD

**Issue by groe** [sunspot/sunspot#673]
The README says:

```ruby
gem 'sunspot_solr' # optional pre-packaged Solr distribution for use in development
```

Why is it not recommended to use `sunspot_solr` in production as well?

**Comment by jasonperrone** [comment]
For me, it's because I wanted a separately installed Solr engine on my production box, and not one embedded in my application's Rails.root directory. Otherwise, every time I deployed the app with capistrano Solr would be deleted, reinstalled and then would have to reindex.

**Comment by bragboy** [comment]
Because it is not intended for full fledged enterprise deployment. Also what @jasonperrone says is right.
