### ISSUE TITLE
Invalid UTF-8 character crashes reindexing

### ISSUE THREAD

**Issue by toothrot** [sunspot/sunspot#688]
Hello!

We have millions of records we are trying to reindex in Sunspot, which is amazing, by the way! 

Receiving a 400 error from Sunspot causes the reindex rake task to crash:

```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {'responseHeader'=>{'status'=>400,'QTime'=>8},'error'=>{'msg'=>'Invalid UTF-8 character 0xfffe at char #40895, byte #39604)','code'=>400}}
```

While we are searching through our data to find the bad character, it would be nice if this didn't cause a complete failure in a multi-hour indexing.

Once we find the invalid record, I will add more details here. Do you have any thoughts on a workaround?

**Comment by carpodaster** [comment]
@toothrot we had a similar problem with control chars that we solved by removing them using Ruby in the `searchable` call:

```ruby
class Example
  searchable do
    description { |item| item.description.to_s.gsub(/[[:cntrl:]]/, ' ') }
  end
end
```

**Comment by toothrot** [comment]
@carpodaster thanks for the tip! I found a solid fix here:

https://github.com/sunspot/sunspot/issues/570

**Comment by mlh758** [comment]
#886 should have fixed this.
