### ISSUE TITLE
Sunspot does not unscope a default scope

### ISSUE THREAD

**Issue by stefanlyew** [sunspot/sunspot#706]
If I have a Model with a default scope:

```ruby
class Product < ActiveRecord::Base
  default_scope { where(active: true) }
end
#app/models/product.rb
```

but I wrap my search in an unscoped block

```ruby
  Product.unscoped do
    Product.search do
      fulltext params[:query]
      any_of do
        with(:active, true)
        with(:active, false)
      end
      order_by(params[:sort], params[:direction]) if params[:sort].present?
      paginate page: params[:page], per_page: 10
      ...
    end
  end
#app/controller/products_controller.rb#index
```

SOLR will still apply the default scope where "products" . "active" = 't'

    SOLR Request (23.7ms)  [ path=select parameters={fq: ["type:Product", "active_b:(true OR false)"], 
    q: "4-", fl: "* score", qf: "part_number_text description_text manufacturer_text distributor_text    
    labor_hours_text programming_hours_text wholesale_price_text retail_price_text", defType: 
    "edismax", start: 0, rows: 10} ] 
    
    Product Load (0.6ms)  SELECT "products".* FROM "products" 
    WHERE "products"."active" = 't' AND "products"."id" IN (343, 314, 454, 445, 269, 436, 438, 449, 
    193, 287)

I tried dot notation and that does not work:
```ruby
Product.unscoped.search do
  ...
end
```

Maybe this could be solved by adding an option to pass unscoped: true to search?

**Comment by stefanlyew** [comment]
unscoped needs to be around the results call, not the search call

```ruby
Product.unscoped do
  @products = search.results
end
```

**Comment by StaverDmitry** [comment]
Hello! Just to mention: that approach totally makes sense when you know the codebase but it's not very intuitive for when you just need it to work. 
Would be great to have it mentioned somewhere in readme because I think it's not a very rare case and we just had a hard time figuring it out, thanks :)
