### ISSUE TITLE
undefined method `create' for ActiveRecord::Relation:Class

### ISSUE THREAD

**Issue by smanvi** [sunspot/sunspot#712]
I made a rails-api project....developed it on windows. The request response work perfectly there. 
I have two tables : 

``` javascript
    class TableOne < ActiveRecord::Base
      self.table_name = "table_one"    #working on an existing db.. not made on rails. 
      has_many :table_twos, foreign_key: "two_id"
      searchable do
          text :title, :stored => true
          integer :status, :stored => true
          string :id, :multiple => true, :stored => true do
                     table_twos.map(&:two_id)
          end
       end
    end
```

``` javascript
class TableTwo< ActiveRecord::Base
  self.table_name = "table_two"
  belongs_to :table_one
end
```

And to search (using sunspot solr) I am using the following in my controller :

``` javascript
@search= TableOne.search do
        fulltext "go"
        all_of do 
            with(:status,1)
            without(:id,nil)
        end
        paginate :page => 1, :per_page => 5
    end
    @search.hits.each do |hit|
        puts hit.stored(:title)
        puts hit.stored(:id)[0]}
    end 
```

In the api that I am hitting.. **there in no db query.** 
Only sunspot search. And it works fine on windows in development environment.

 I took it to linux server.
When I `rake sunspot:solr:start` and `rake sunspot:solr:reindex`, the indexes are made correctly. No issues there. 
But on hitting the api, I get this error : 

``` javascript
    undefined method `create' for ActiveRecord::Relation:Class
```

Any help ?

**Comment by ethirajsrinivasan** [comment]
@smanvi the issue doesnt seem to come from sunspot.Can you provide info on where you are calling the create method.
