### ISSUE TITLE
[Solr 5] Instead of the number of returns an array

### ISSUE THREAD

**Issue by voodee** [sunspot/sunspot#722]
sunspot v 2.2.0

```
searchable do
    integer :id, :stored => true
end
```

In console:
```
Obj.search.hits[0].stored(:id)
```

Solr 4 return `3`, but Solr 5.2.1 return `[3]`.

**Comment by bragboy** [comment]
Tried with the 2.2.0 bundled solr and it worked fine for me. Even cross verified against the master branch.

```
2.2.1 :001 > Article.reindex
[2015-11-11 17:59:06 +0530] Start Indexing
[2015-11-11 17:59:06 +0530] Completed Indexing. Rows indexed 50. Rows/sec: 799.6289721569192 (Elapsed: 0.062529 sec.)
 => nil 
2.2.1 :002 > Article.search.hits[0].stored(:id)
 => 1 
```

Can you show me a sample app that has this problem. If its still a problem - feel free to reopen.
