### ISSUE TITLE
Get location distance in result

### ISSUE THREAD

**Issue by guigeekz** [sunspot/sunspot#725]
Hello,

when I'm using the filter with radius :

<code>Post.search do
  with(:location).in_radius(32, -68, 100)
end</code>

Is it possible to get the calculated distances into my results for each Post object?

Thank you for this nice gem!

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
