### ISSUE TITLE
reindexing throws Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by pamio** [sunspot/sunspot#727]
Hi, 
I've basically setup solr on my machine and I'm trying to reindex the models. When call the rake task from terminal `bundle exec rake sunspot:reindex` it throws this error. 

I'm using ruby on rails and sunspot to get solr running for full text search. I'm sure my db config is fine as I could connect to rails console and fetch data. 

Here is the trace 

      Error using progress bar: Access denied for user 'root'@'localhost' (using password: YES)
      rake aborted!
      Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-    3.2.3/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord- 3.2.3/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:303:in `new_connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:313:in  `checkout_new_connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-    3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:237:in `block (2 levels) in checkout'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:232:in `loop'
     /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:232:in `block in checkout'
     /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:229:in `checkout'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:95:in `connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:398:in `retrieve_connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:168:in `retrieve_connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/connection_adapters/abstract/connection_specification.rb:142:in `connection'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/octopus-e6d8b75ae589/lib/octopus/model.rb:64:in `connection_with_octopus'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/model_schema.rb:137:in `quoted_table_name'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/relation/delegation.rb:7:in `quoted_table_name'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/relation/batches.rb:87:in `batch_order'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/relation/batches.rb:65:in `find_in_batches'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/gems/activerecord-3.2.3/lib/active_record/querying.rb:8:in `find_in_batches'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot-6e87517cfffb/sunspot_rails/lib/sunspot/rails/searchable.rb:254:in `solr_index'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot- 6e87517cfffb/sunspot_rails/lib/sunspot/rails/searchable.rb:198:in `solr_reindex'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot-6e87517cfffb/sunspot_rails/lib/sunspot/rails/tasks.rb:58:in `block (3 levels) in <top (required)>'
      /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot-6e87517cfffb/sunspot/lib/sunspot/class_set.rb:16:in `each'
       /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot-6e87517cfffb/sunspot/lib/sunspot/class_set.rb:16:in `each'
       /home/pamio/.rvm/gems/ruby-1.9.3-p547/bundler/gems/sunspot-6e87517cfffb/sunspot_rails/lib/sunspot/rails/tasks.rb:57:in `block (2 levels) in <top (required)>'
       /home/pamio/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
       /home/pamio/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'
       Tasks: TOP => sunspot:reindex
      
I could also connect to mysql using `mysql -u root -p` so I dont understand why would solr not be able to connect to mysql with the same config. 

Thanks

**Comment by IslamAzab** [comment]
@pamio Are you sure of your password ? It seems there is no password and you are using one.

**Comment by pamio** [comment]
@IslamAzab, its rectified now. I had another db connected to which I didnt have access and hence the error. Thanks for the help.
