### ISSUE TITLE
document count doesn't match database record count

### ISSUE THREAD

**Issue by gswartz777** [sunspot/sunspot#730]
We have 12,245,006 records in our mysql database that we're trying to index in solr.  When I run the following command...

rake sunspot:reindex:parallel[750,Company,7] RAILS_ENV=local_production

it processes for 10.5 hrs and I'm left with 1,761,195 documents in my solr index.   I don't have any errors in the console nor in any log files to determine why the number of solr documents doesn't more closely match my database count.  

I ended up finding a record that was not in the solr index and pulled it up in our rails app, clicked update and now it's in the solr index.  This was set up by a previous developer and I'm not well versed with all of the code, so I'm not quite sure where to start looking for the cause.  I did check the model code to see if there was anything that would keep it from indexing the model, but found nothing.  Is there a limit to the number of records sunspot can index?

**Comment by sahil290791** [comment]
Check if you have any field which is having any condition before the records are being indexed, which might be filtering out few records.

**Comment by ewlarson** [comment]
12M records is a lot to index via Sunspot, and spending 10+ hours to reindex everything via rake sunspot just isn't worth the wait.  Here's a better way:

1. Index 1000 sample records into Solr via Sunspot
2. Use the Solr Admin Schema Browser to see what dynamic fields end up created in your Solr index
3. Learn how to use Solr's Data Import Handler, which can pull data from a database via JDBC into Solr blazing _fast_.

It'll take some time and effort, and frustration and learning, but ultimately you'll be able to index the 12M records in about 10-20 minutes.  If you're careful to adhere to Sunspot's schema expectations, you'll still be able to use Sunspot in your Rails app without noticing the difference at all.  New records added via your Rails app will "just work".

Also, I've found that at 12M records (18M+ in my app), you'll likely need to give more than the default 512MB to the java heap -- Solr is gready.  Try starting your Solr instance with much more memory, something like: bin/solr start -m 1g
