### ISSUE TITLE
Facet exclude cannot contain fulltext searches

### ISSUE THREAD

**Issue by sdhull** [sunspot/sunspot#732]
```ruby
filters = []
Model.search do
  with :organization_id, organization_id
  fulltext(keywords).each do |field|
    filters << field
  end
  filters << with :categories, categories if categories.present?
  facet :categories, exclude: filters
end
# stack level too deep
```

Technically, I'd love the inverse of the `:exclude` option for facets (call it `:include`), so I could have facet values that only count a given set of filters (for me, I'd only include the organization_id filter).

**Comment by bragboy** [comment]
Thanks for reporting this issue. Sunspot is a mere wrapper for the Solr enginer, can you please provide examples the current and expected queries fired against Solr?

**Comment by sdhull** [comment]
Hi @bragboy -- thanks for the reply. After talking with my in-house Solr expert, I guess what I'm asking for is not actually possible with Solr. :disappointed:

**Comment by bragboy** [comment]
@sdhull - Thanks for reverting back!

**Comment by bragboy** [comment]
oops! reopened accidentally
