### ISSUE TITLE
Solr 5 multicore and sunspot.yml - bad url component

### ISSUE THREAD

**Issue by carstengehling** [sunspot/sunspot#734]
I'm currently trying to setup Solr 5.3.1 with multiple cores. Right now I have made a core on this URL:

    http://localhost:8983/solr/#/gipote

But I find it difficult to configure the Sunspot 2.2 gem correctly in my Rails app. I am running Ruby 2.2, Rails 3.2 (the latest update that supports Ruby 2.2), and my sunspot.yml file looks like this:

    production:
      solr:
        hostname: localhost
        port: 8983
        log_level: WARNING
        path: ???

It's the path that gives me problems. I've tried to set it to "/solr/gipote", which gives me "bad request". I've also tried to set it to "/solr/#/gipote", but then rake reindex quits on startup with this stacktrace:

    URI::InvalidComponentError: bad component(expected absolute path component): /solr/#/gipote
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/sunspot_rails-2.2.0/lib/sunspot/rails.rb:61:in `slave_config'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/sunspot_rails-2.2.0/lib/sunspot/rails.rb:38:in `build_session'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/sunspot_rails-2.2.0/lib/sunspot/rails/railtie.rb:5:in `block in <class:Railtie>'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
    /home/gipote/site/config/environment.rb:5:in `<top (required)>'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/application.rb:103:in `require_environment!'
    /usr/local/rvm/gems/ruby-2.2.1@gipote/gems/railties-3.2.22/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'

So what should I set the path to? I've not been able to find any hints on the net - spent the past 2 hours searching.

**Comment by bragboy** [comment]
Usually it is enough for you to set the default collection name/core name. If your core's name is gipote you could set path to `path: /solr/gipote`

**Comment by carstengehling** [comment]
If I do that and run e.g. reindex, it fails with this Bad Request error:

**Comment by carstengehling** [comment]
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
    Error: {'responseHeader'=>{'status'=>400,'QTime'=>2454},'error'=>{'msg'=>'undefined field type','code'=>400}}

    URI: http://localhost:8983/solr/gipote/update?wt=ruby
    Request Headers: {"Content-Type"=>"text/xml"}
    Request Data: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><delete><query>type:Ad</query></delete>"

In Solr's web admin I also cannot access the core without using the # sign

**Comment by carstengehling** [comment]
Closing this again - it turned out, that the path /solr/gipote was just fine. The errors origined in me upgrading sunspot and not changing my DSL code for each model...

**Comment by bragboy** [comment]
@carstengehling - Thanks for reverting!
