### ISSUE TITLE
sunspot:reindex in sunspot_rails 2.2.0: error under Rails 3.0

### ISSUE THREAD

**Issue by showaltb** [sunspot/sunspot#739]
Using sunspot_rails 2.2.0

I have an app on Rails 3.0.20 that uses the date_validator gem. Running `rake sunspot:reindex` gives an error:

    $ bundle exec rails --version
    Rails 3.0.20
    $ bundle exec rake sunspot:reindex
    rake aborted!
    NoMethodError: undefined method `instance' for DateValidator::Engine:Class

The error is coming from https://github.com/sunspot/sunspot/blob/master/sunspot_rails/lib/sunspot/rails/tasks.rb#L34:

    Rails::Engine.subclasses.each{|engine| engine.instance.eager_load!}

Rails 3.0 engines do not implement `instance`. I tested under Rails 3.1.12 and `instance` is implemented there.

Probably should just bump the minimum Rails version in the gemspec to 3.1.

sunspot_rails 2.1.1 still works under Rails 3.0.

**Comment by bragboy** [comment]
We will have consider both the options - whether to drop support entirely for 3.x given 5.x is around the corner. Or perhaps patch it temporarily to support 3.x. Thank you for reporting this bug!

**Comment by showaltb** [comment]
FWIW, the fix for #763 does not address this issue. The `sunspot:reindex` task still fails under Rails 3.0 for the reason explained in the original report.
