### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by ArmyAndy** [sunspot/sunspot#744]
I have configured solr with basic auth successfully. However it seems for the gem - https://rubygems.org/gems/sunspot-rails-http-basic-auth/versions/0.0.2 to work we need to use sunspot 1.2.1 forcing me to downgrade from 2.2.2

Can you please tell em how I can configure http basic auth within my sunspot.yml for sunspot 2.2.2?

**Comment by visitvinoth** [comment]
sunspot-rails-http-basic-auth should upgrade their version to support sunspot-2.2.2. Then only you can continue using 2.2.2.
