### ISSUE TITLE
Pagination mess

### ISSUE THREAD

**Issue by bolshakov** [sunspot/sunspot#745]
I have an API with limit/offset based pagination and need to render pagination info for each collection response. This info looks like this:

``` ruby
{
  pagination: {
    limit: 2, 
    offset: 4,
    count: 1,
    total_count: 5
  }
}
```

I've figured out how to perform pagination using `limit` and `offset` values but it is impossible to extract this values from `PaginatedCollection` since it does not keep `offset` value. 

I suggest to refactor `#paginate`, to provide more flexible interface which matches both page-based and limit/offset based needs:

``` ruby
# @param padding [Integer] pad number of records before pagination
# @param page [Integer] number of page
# @param per_page [Integer] number of records on each page
def paginate(padding: 0, page: 1, per_page:)
# ...
end
```

I also suggest to refactor `PaginationCollection` to remove all duplicated names and return the same pagination options as passed to `#paginate` method enriched with total count and count:

What do you think? Any concerns?

**Comment by mlh758** [comment]
Closing this since it went 5 years without comment. The API change probably won't end up happening.
