### ISSUE TITLE
Can I disable reindexing while save my model?

### ISSUE THREAD

**Issue by sunnmas** [sunspot/sunspot#748]
I'd like to disable solr reindexing, while save my model. Example:

def show
  @item = Item.where(params[:id]).first
  @item.views_count += 1
  @item.save
  render :show_item
end
Field views_count is not searchable. But solr take 2 seconds while saving my model. Can I switch off solr reindexing at this case?

**Comment by sdhull** [comment]
You can do

```ruby
class Item < ActiveRecord::Base
  searchable auto_index: false do
    # field list
  end
end
```

This will make it so it never indexes upon save, so you'll need to manually index records this way. I recommend you index in the background using sidekiq or some other background processing.

**Comment by sdhull** [comment]
Lots of other options too... you could batch update index every x minutes using cron or other schedulers

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
