### ISSUE TITLE
Breaking changes to configuration generation in 2.2.3 version?

### ISSUE THREAD

**Issue by reconstructions** [sunspot/sunspot#750]
When upgrading from version 2.2.0 to version 2.2.3 of the sunspot_rails/sunspot_solr/sunspot gems, both my test and development Solr servers broke and could not be fixed by the usual cycle of regeneration and reindexing:

Before:
sunspot (2.2.0)
sunspot_rails (2.2.0)
sunspot_solr (2.2.0)

After:
sunspot (2.2.3)
sunspot_rails (2.2.3)
sunspot_solr (2.2.3)

Restarting my servers produced a series of errors concerning the malformation of the 'solr.xml' config file:

582  ERROR (main) [   ] o.a.s.s.SolrDispatchFilter Could not start Solr. Check solr/home property and the logs
595  ERROR (main) [   ] o.a.s.c.SolrCore null:org.apache.solr.common.SolrException: Should not have found solr/cores
Please upgrade your solr.xml: https://cwiki.apache.org/confluence/display/solr/Format+of+solr.xml

Taking a look at the cwiki.apache.org page it was clear that the format of the solr.xml had completely changed and it would need to be regenerated.

In version 2.2.0, the frequently corrupted contents of the /solr folder could be regenerated by deleting them and running 'rake sunspot:solr:run'.  So I tried that.  

In version 2.2.3 it appears that a functional version of the /solr folder is not produced by running the rake tasks.  Only a few empty directories are added, so the servers naturally fail to start with a '/solr must contain a solr.xml file!' error.

I looked into patching the botched configuration created by the rake task by copying the sunspot_rails gem configuration per the instructions: "create the directory RAILS_ROOT/solr/conf, and copy in the contents of the Solr gem's solr/solr/conf directory".

Assuming the 'Solr gem' referred to in the instructions is the sunspot_solr repo, the /solr/solr folder contains no /conf directory, but instead a /configsets/sunspot/conf folder which I tried copying to the expected place (/solr/solr/conf), but that only produced a bunch of errors.  

I also tried copying the contents of the /sunspot/sunspot_solr/solr/solr/solr.xml file to the /solr/solr.xml config file with my working 2.2.0 setup, and that actually worked pretty well (a server started), expect port 8983 is hard coded in that solr.xml, so it ignored my config/sunspot.xml and didn't start my development and test servers.

I am hoping that I am completely missing something, because it would be a shame if convention were replaced by misconfiguration as far as this repo was concerned...

**Comment by maokomioko** [comment]
Just had the same problem, that's how new default config should look like. (.xml renamed to .txt)
[solr.txt](https://github.com/sunspot/sunspot/files/109248/solr.txt)

**Comment by reconstructions** [comment]
That is not well-formed XML, it has only an opening <solr> tag used as a closing tag, but a solution will presumably use the "[core discovery](https://cwiki.apache.org/confluence/display/solr/Moving+to+the+New+solr.xml+Format)" format.

**Comment by maokomioko** [comment]
The ending got truncated, but the idea is pretty clear imho.

**Comment by reconstructions** [comment]
This is the correct format for the solr.xml:

```xml
<solr>

  <solrcloud>

    <str name="host">${host:}</str>
    <int name="hostPort">${jetty.port:8983}</int>
    <str name="hostContext">${hostContext:solr}</str>

    <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>

    <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
    <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
    <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>

  </solrcloud>

  <shardHandlerFactory name="shardHandlerFactory"
    class="HttpShardHandlerFactory">
    <int name="socketTimeout">${socketTimeout:600000}</int>
    <int name="connTimeout">${connTimeout:60000}</int>
  </shardHandlerFactory>

</solr>
``` 

The sunspot gem will generate this solr.xml file (using the correct core discovery format), but only if you delete your /solr directory and restart the server.  Also be careful to kill any running solr instances.
