### ISSUE TITLE
spellcheck_collation is nil if there's only one suggestion

### ISSUE THREAD

**Issue by JasonBarnabe** [sunspot/sunspot#752]
If `solr_spellcheck['suggestions'].length` is 1, then `spellcheck_collation` returns `nil`. https://github.com/sunspot/sunspot/blob/327c7e4e2d3a9ad8351e8941d646e37088224341/sunspot/lib/sunspot/search/standard_search.rb#L57

I was trying to use `spellcheck_collation` as a "did you mean..." hint. It would be better if I didn't have to check to see if the user entered 2 or more terms to be able to use this.

**Comment by CausaMortis** [comment]
@JasonBarnabe it sounds to me like you would need to use the Suggester functionality for that.

Just curious though as I am struggling getting `spellcheck_collation` to work myself. Were you able to get back a collation query if you increased the amount of suggestions that Solr returns by setting the `spellcheck.count` option?

For me, it is always nil even though the XML output seems fine when I view the same query in the admin panel..
