### ISSUE TITLE
2.2.0 -> 2.2.1 breaking change to indexed ID

### ISSUE THREAD

**Issue by bithive** [sunspot/sunspot#755]
In 2.2.0 the value returned by `to_param` was being used as the record ID in the index.  Since I use UUIDs for all external references, I would get back results like `FoobarIndex 340b0d09-3008-43e6-9139-c4a0031b8e39`.

After upgrading to 2.2.4 this mysteriously changed to use just the ID, so I started getting results like `FoobarIndex 12`.

Reverting to 2.2.0 (and reindexing) without changing any of my code seems to have fixed the issue.

**Comment by bragboy** [comment]
Can't you do complete reindex and start following the new id for index ?

**Comment by bithive** [comment]
I could but I don't want to for a few reasons:

1. I want to use the UUID, which is why Rails has `to_param`.  The integer primary key is a predictable sequence so I don't want to expose it anywhere that clients might see it (like in Solr indexes)
2. I'd have to rewrite a bunch of client code since the Solr index is consumed by more than just Sunspot
3. I don't want to have to regenerate my entire index, which is rather large, just because I did a "bundle update" and something fundamental like "which attribute to use as the ID" has changed between releases.

Would it be helpful if I tracked down where this change occurred and submitted a pull request that restores the expected behavior? (That ActiveRecord models in a Rails app use `to_param` to generate external references)

**Comment by bragboy** [comment]
Sure, submit one I shall review it.

**Comment by bithive** [comment]
FYI: This is the commit where the behavior changes: https://github.com/sunspot/sunspot/commit/b012822d016335b9d469f5a666f9b9123e3a7ece

I suspect it has something to do with the change to `document_for` where `Adapters::InstanceAdapter.adapt(model).index_id` gets replaced with `Adapters::InstanceAdapter.index_id_for(clazz.name, id)` but I'll have to do more digging to be sure.

**Comment by bithive** [comment]
Pull request here: https://github.com/sunspot/sunspot/pull/758

I'm not sure what the new atomic update code path is for, so I tried to make a clean separation that allows for the 2.2.0 behavior.
