### ISSUE TITLE
How can I get termfreq result using Sunspot

### ISSUE THREAD

**Issue by jstdoit** [sunspot/sunspot#756]
As mentioned in title, I just want to get some term's freq in document, and I referred to page http://wiki.apache.org/solr/FunctionQuery#termfreq, but I do not know how to use it in sunspot.

Anyone can help me?

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
