### ISSUE TITLE
2 Rails apps, 1 Sunspot instance

### ISSUE THREAD

**Issue by DaniG2k** [sunspot/sunspot#757]
Is there a guide on how to set up 2 Rails apps with 1 Suspot instance, all running on the same server? I haven't been able to set this up for the life of me.

Any help is much appreciated.

Thanks :smiley:

**Comment by bragboy** [comment]
It should be possible. Are you planning on using the bundled sole or do you have one running independently?

**Comment by DaniG2k** [comment]
I have an app with the sunspot solr gem (so I'm assuming it's the bundled one) and I'd like both apps to use the same solr instance.

I believe I need to give the indices two different names (multi core?) since both have a model called Article that I want to be indexed.

**Comment by DaniG2k** [comment]
The bundled solr.

**Comment by itsmechlark** [comment]
@DaniG2k, I think the better setup for that is deploying standalone solr via tomcat.
