### ISSUE TITLE
Cannot facet with joined attribute

### ISSUE THREAD

**Issue by metalicjames** [sunspot/sunspot#764]
I'm joining with another table in my search using the following call:

join(:attribute_option_id, :target => ToggleOption, :type => :integer, :join => { :from => :product_id, :to => :id })

Both models are set up correctly and I can filter by with(:attribute_option_id, 1). However when I try and use facet(:attribute_option_id) I always get 0 rows from the result. 

What could be going wrong?

**Comment by bragboy** [comment]
Can you paste your expected and actual SOLR query?

**Comment by bikeath1337** [comment]
@metalicjames did you resolve this?

**Comment by metalicjames** [comment]
Sadly not, my understanding is that that isn't possible due to Solr
limitation rather than anything wrong with Sunspot.
