### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by dza2000** [sunspot/sunspot#765]
I'm looking to use Solr on a Rails 5 project, but it doesn't seem to be compatible.  Am I missing something?  Starting it gets this error:
```
/Users/Don/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sunspot_rails'. (Bundler::GemRequireError)
	
```

**Comment by vnatarajan-rpx** [comment]
@dza2000,
I get sunspot(2.2.4) working fine with rails 5.0.0.beta3. 
If possible, please post you Gemfile or specific gems and their versions.

**Comment by bragboy** [comment]
Please reopen this with detailed info
