### ISSUE TITLE
README.md between syntax

### ISSUE THREAD

**Issue by Riveascore** [sunspot/sunspot#768]
You use commas instead of ellipsis at the end of [this block of code](https://github.com/sunspot/sunspot#joins) in your README.

It should instead be:
`with(:photos_created).between(Date.new(2011,3,1)..Date.new(2011,4,1))`

**Comment by bragboy** [comment]
please submit a Pull Request, i can merge it

**Comment by ashishprajapati** [comment]
@bragboy I have opened a PR over there 
https://github.com/sunspot/sunspot/pull/772
