### ISSUE TITLE
Is it possible to cut a new version with the latest in master?

### ISSUE THREAD

**Issue by mdayaram** [sunspot/sunspot#773]
Our team is depending on changes that have been merged in a few weeks ago but haven't been cut yet.  It would be tremendously helpful to be able to point our app to a specific version.

**Comment by ashishprajapati** [comment]
Hey @mdayaram 
Hope you are doing well!

The only way to maintain the code base of sunspot as per your app criteria, please create a fork of sunspot latest code base and than take the clone at local after that update your fork where the last best was working for your app using the below mentioned command and push back to github fork repo of you forcefully.

`
git reset --hard [commit number]
git push origin master -f

`

After that set the path of your fork repo to the sunspot gem. 
gem 'sunspot_rails', :git => 'git://github.com/ashishprajapati/sunspot.git'

thanks

**Comment by bragboy** [comment]
@mdayaram - Just gave the gem a minor bump - your change should be in it. Just do a bundle update for sunspot

**Comment by mdayaram** [comment]
Thanks!
