### ISSUE TITLE
Does Sunspot::Rails.build_session need to initialize everytime in sidekiq?

### ISSUE THREAD

**Issue by dotswing** [sunspot/sunspot#774]
Hello, I saw the update with the threading part about two weeks ago and wonder if I need create session by running 

```
session = Sunspot::Rails.build_session  Sunspot::Rails::Configuration.new
Sunspot.session = session

Sunspot.session.index! ...

```
Every time when sidekiq perform a task? Or I just run in once somewhere? 

Thanks.

**Comment by ethirajsrinivasan** [comment]
Please use StackOverflow or any other forum for questions/help, where a wider community will be able to help you. Issues tracker are for issues only.

**Comment by tquill** [comment]
Would you mind clarifying the docs a bit more on this?  I can't get it to work with sidekiq.
