### ISSUE TITLE
 session.commit_if_dirty soft_commit error

### ISSUE THREAD

**Issue by andreipot** [sunspot/sunspot#775]
@alindeman  @nz 
Thanks for your great work. I've been using sunspot_rails gem for serach in my rails project.

I get this error.
wrong number of arguments (1 for 0)

from this call.
    # Sends a commit (soft or hard) if the session is dirty (see #dirty?).
    #
    def commit_if_dirty(soft_commit = false)
      session.commit_if_dirty soft_commit
    end
any idea?

**Comment by phantompatrol** [comment]
Running into the same issue. Very odd.

**Comment by ethirajsrinivasan** [comment]
@andreipot @phantompatrol can you please provide more info on the issue

**Comment by DevilalDheer** [comment]
Facing same issue during rails upgrade 3.2 to 4.2.3
Error message is 'wrong number of arguments (1 for 0)'

```
 def commit_if_dirty(soft_commit = false)
      session.commit_if_dirty soft_commit
 end
```
Initially sunspot_rails version is 2.0.0 that time I am facing issue is like:

> /activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- active_support/core_ext/object/to_json (LoadError)

after that updated sunspot_rails gem with 2.2.0 & getting this error.

@ethirajsrinivasan More Details:
gem 'sunspot_rails',"~> 2.2.0"
ruby: 2.2.4
rails: 4.2.3
puma

**Comment by mlh758** [comment]
I am closing this due to age.
