### ISSUE TITLE
Error using with(:location).near(lat, lon, options = {})

### ISSUE THREAD

**Issue by Shinta** [sunspot/sunspot#776]
I ran a simple search:

``` ruby
search = User.search do
  with(:location).near(-25.263740, -57.575926)
end
```

And I'm getting: 

```
RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: 'Point must be in \'lat, lon\' or \'x y\' format: 6ex03bfkp9tb','code'=>400}}
```

Ruby 2.2.4, Rails 4.2.3, Sor 5.5.0, Sunspot/SunspotRails 2.2.5.

Any help?

**Comment by Shinta** [comment]
I did what I needed with `order_by_geodist` but It will be cool to use near

**Comment by sakthivelsekar33** [comment]
@Shinta **near** function should be applied to **geohash field(location field type)**, but not on **latlon** field type

from documentation,

> Perform a Geohash-based location restriction for the given `location` field.

the right way to use this is
```
     searchable do                                                                                                                     
       location(:coordinates, stored: true) { sunspot::util::coordinates.new(lat, lng) }
     end

     User.search do
        with(:coordinates).near(49.503252, -1.32789)
      end

```

This issue can be closed.
