### ISSUE TITLE
rails 4 support for 2.0.0

### ISSUE THREAD

**Issue by sevaorlov** [sunspot/sunspot#777]
Hi, can you release v2.0.1 with rails 4 support? We use Solr 3 and can't update to v2.1.0 because of it, but we plan to upgrade Rails to version 4 and right now sunspot rails have problems with it.

I've created 2-0-0-stable branch in my fork and created PR to it. 
https://github.com/sevaorlov/sunspot/pull/1/files

If you create 2-0-0-stable version branch in this repo I can open request to it.

Thanks

**Comment by vsorlov** [comment]
pr is in progress, I'm trying to find a way to support rails 4 in v2.0.0

**Comment by vsorlov** [comment]
actually maybe it is possible to use sunspot v2.1.0 with Solr 3?

**Comment by bikeath1337** [comment]
Closing this as Sunspot supports Rails 4.

**Comment by sevaorlov** [comment]
@bikeath1337, I'm asking to release v2.0.1 with Rails 4 support as v2.0.0 doesn't have it and we can't update to v2.1.0 as we use Solr 3.

**Comment by bikeath1337** [comment]
OK, that makes sense. I misunderstood. 

However, if all you would like to do is to get a version of the gem that works with your preferred versions, there is no need for me to do anything as we don't want to be creating dead-end branches for single users.

Why don't you just use your branch and create a reference in your Gemfile to it? That should give you time to (ultimately) upgrade.

**Comment by sevaorlov** [comment]
@bikeath1337, yes, that is what I did. I just though it might be helpful for someone and our Gemfile will look prettier.  :)
