### ISSUE TITLE
Instructions on how to run sunspot specs?

### ISSUE THREAD

**Issue by serggl** [sunspot/sunspot#781]
Im about to submit PR to this repo and Im trying to run bundled specs...
I can't find any instructions on how to run tests in this repo...
Could someone route me? 
Im currently running `rake .` or `rake spec RAILS=3.0.0` and they both fail with error:
```
Using sunspot lib at /Users/sergeyglukhov/projects/sunspot/sunspot/lib
Running specs against Rails 3.0.0...
bundle exec rspec spec/*_spec.rb --color
/Users/sergeyglukhov/projects/sunspot/sunspot_rails/tmp/rails_3_0_0_app/vendor/bundle/gems/activesupport-3.0.20/lib/active_support/values/time_zone.rb:272: warning: circular argument reference - now
/Users/sergeyglukhov/projects/sunspot/sunspot_rails/tmp/rails_3_0_0_app/vendor/bundle/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require': cannot load such file -- test/unit/assertions (LoadError)
```

**Comment by serggl** [comment]
oh, I figured it out.
There must be somewhere in the README that **ruby 2.1.8 only** is required to run specs.
I had 2.3.0 installed and it isn't compatible with Rails 3 related specs

**Comment by bikeath1337** [comment]
@serggl Thanks for the heads-up. If you would like to submit a PR to clarify the docs, we'd welcome that.
