### ISSUE TITLE
Reindexing objects is not automatically running on ruby on rails

### ISSUE THREAD

**Issue by mzane42** [sunspot/sunspot#783]
Hi,
i'm using Sunspot Solr for indexing and searching in our Ruby on Rails application with MangoDB
database (Mongo mapper)

The searching works well, but objects aren't automatically indexed to Solr when i make changes on my database.

I tried manually index on a class itself:

`Top.reindex
Sunspot.commit`

Or, I added on sunspot.yml :
`auto_commit_after_request: true
`
I also autocommit with some interval on solrconfig.xml :    

`<autoCommit>`
    `<maxDocs>10000</maxDocs>`
    `<maxTime>15000</maxTime>`
`</autoCommit>`

All this solutions failed to reindex automatically my objects, unless i reindex all objects with rake task :

`bundle exec rake sunspot:reindex
`

Any other solutions ?

Thanks a lot.

**Comment by erhimanshugoyal** [comment]
Same Problem, if you have found a solution please tell

**Comment by mzane42** [comment]
@erhimanshugoyal :

You can try to doing some manual indexing on involved models, similar to the ActiveRecord hooks, for instance on a User model:

```
after_save { |user| Sunspot.index!(user) }
after_destroy { User.reindex; Sunspot.commit }
```

tell me if it works ! :)

**Comment by rafalklo** [comment]
I did not try this, but there is a gem to integrate Mongo with Sunspot, maybe you guys should check it out.

https://github.com/derekharmel/sunspot_mongo

**Comment by mlh758** [comment]
Closing this due to age.
