### ISSUE TITLE
Exclude objects from index

### ISSUE THREAD

**Issue by 23tux** [sunspot/sunspot#785]
Hi,

is it possible to exclude objects from indexing completely? I have a model where half of the DB records are just stored for history purpose. I have to exclude them in every search with a check to `available_on: nil`.

So I'm searching for a way to delete an entire object from index when a certain condition is met (in my case `available_on: nil`), and prevent a re-index when this condition is met.

Is something like this possible? Or am I missing a feature?

**Comment by bikeath1337** [comment]
Hi, @23tux ,

Yes, you can choose to define one or more methods for `searchable`'s `if` and `unless` methods. To use multiple methods, place the methods in an array. Here is some scaffolding code:

```ruby
class Thing < ActiveRecord::Base
  #  searchable(unless: [:soft_deleted?, :removed?]) do
  searchable(unless: :soft_deleted?) do
    string :name
    text :description
  end

  def soft_deleted?
    soft_deleted
  end

end
```
