### ISSUE TITLE
Sunspot lacks field list support

### ISSUE THREAD

**Issue by antonyr** [sunspot/sunspot#790]
I would like to see a way to support field list in the following manner in solr sunspot.

```ruby
Post.search do
  with(:blog_id, 1)
  field_list [:blog_id, :title]
end
```

**Comment by serggl** [comment]
@antonyr @bragboy Does this suppose to work? I cant make this work in my project unless I change to something like

```ruby
Post.search do
  with(:blog_id, 1)
  field_list [:blog_id_is]
end
```

**Comment by serggl** [comment]
also `field_list` should contain `:id` or calling `.hits` on search objectwill fail with
```
NoMethodError: undefined method `match' for nil:NilClass
Did you mean?  catch
from /Users/sergeyglukhov/.rvm/gems/ruby-2.3.1@offgrid/bundler/gems/sunspot-5aec95d91730/sunspot/lib/sunspot/search/hit.rb:30:in `initialize'
```

**Comment by serggl** [comment]
the idea behind this is great, but seems like it was not fully implemented

**Comment by markmcdonald51** [comment]
Does this work? 
query.hits
eg,  [#<Sunspot::Search::Hit:MetaUdt11Product 1>,
 #<Sunspot::Search::Hit:MetaUdt11Product 2>,
 #<Sunspot::Search::Hit:MetaUdt11Product 3>,
 #<Sunspot::Search::Hit:MetaUdt11Product 4>,
 #<Sunspot::Search::Hit:MetaUdt11Product 5>,
 #<Sunspot::Search::Hit:MetaUdt11Product 6>,

how can I get the id out of the above...it seems when I add field_list in it doesn't select out the right fields so I assume I have to do it myself eg, ids = query.hits.map{|h| h.stored(:body)}     which doesnt work either. Thanks in advance, mark

**Comment by serggl** [comment]
@markmcdonald51 I believe this was fixed and the fix is on the master branch, but not yet released to rubygems. But you could use github as a source in your Gemfile ofcourse

**Comment by markmcdonald51** [comment]
Thanks serggl. Maybe I will add it back when it's in master. For now I just went thru the base code and got this working

where(id: query.hits.map(&:primary_key))

which works for me for now. THanks for the response!
