### ISSUE TITLE
Query group results not returning all results?

### ISSUE THREAD

**Issue by depl0y** [sunspot/sunspot#792]
Since today I have been playing around with query groups for a small test I am running.

I have defined 2 groups in my query, 1 filters before a certain datetime, the other after the datetime. The following is a simplified example of my groups setup.

```
group do
  query "before" do
    with(:planned).less_than mydate
  end
  query "after" do
    with(:planned).greater_than mydate
  end
end
```

After the query has been performed, I loop through my groups and I see the following results:

```
results.group(:queries).groups.each do |g|
  group_total = g.total
  group_results_count = g.results.count
end
```

query `before`:
`group_total` = 2
`group_results_count` = 1

query `after`:
`group_total` = 3
`group_results_count` = 1

The result count for my group is always 1. The **total** value is actually correct, I have double checked this through the Solr administration panel.

Am I misunderstanding something here, or do groups work differently from what I expect.

I am running on Solr 5.3.1

**Comment by bragboy** [comment]
Did you inspect the SOLR Query that gets fired during your query execution? Can you paste the XML or JSON output ? That could clearly tell whats going on.

Also, these kind of questions are best suited to be asked on Stackoverflow.
