### ISSUE TITLE
Deprecation warning in Rails 5

### ISSUE THREAD

**Issue by hvenables** [sunspot/sunspot#794]
Rails 5.0.0, when running sunspot_rails 2.2.5 gives me the deprecation warning (alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super.) about alias_method_chain which is called in

https://github.com/sunspot/sunspot/blob/master/sunspot_rails/lib/sunspot/rails/solr_instrumentation.rb#L7

**Comment by bragboy** [comment]
@hvenables - I am currently working on this.

**Comment by serggl** [comment]
any luck resolving this @bragboy ?
