### ISSUE TITLE
Empty results 

### ISSUE THREAD

**Issue by ferryphang** [sunspot/sunspot#807]
Hi i have just started to use sunspot ( sunspot_rails (2.2.5) ) and i got a problem my query return empty results.
i have run

```
rake sunspot:reindex
```

and here is my code can anybody help with this?
Model
![applicant](https://cloud.githubusercontent.com/assets/4382692/17781820/130a9bea-659b-11e6-87f8-8fc99f1b5eb2.png)
Query rails console
![query](https://cloud.githubusercontent.com/assets/4382692/17781826/18bf24c0-659b-11e6-9b82-86e4f269d25d.png)

**Comment by DaniG2k** [comment]
Similar issue here

**Comment by bragboy** [comment]
What does `query.hits` return ?

**Comment by softr8** [comment]
`fulltext` searches over all columns defined with `text` and skip `string` columns in the index try with:
```
class Applicant < ActiveRecord::Base
  searchable do
    text(:name) { [:full_name, :full_name_identity_card, :identity_card_number].join(' ') }
  end
end
```

**Comment by pkandhasamyc-rpx** [comment]
The above code also not working, 
text fields will be full-text searchable. Other fields (e.g., integer and string) can be used to scope queries.

if you want to use those fields for full text define them as text fields

**Comment by ponnusamygit** [comment]
The above code also not working, 
text fields will be full-text searchable. Other fields (e.g., integer and string) can be used to scope queries.

if you want to use those fields for full text define them as text fields
