### ISSUE TITLE
How to avoid having a direct connection between model and Sunspot objects?

### ISSUE THREAD

**Issue by ChristofferJoergensen** [sunspot/sunspot#809]
I have a `Product` model that is currently searchable on the `name` and `sku` fields. As you can see I am encrypting these fields, but storing the corresponding Sunspot objects unencrypted:

``` ruby
class Product
  include Mongoid::Document
  include Mongoid::Timestamps
  include Sunspot::Mongo

  searchable auto_index: false do
    string  :webshop_id,  :stored => true
    text    :remote_id, :stored => true do
      SymmetricEncryption.decrypt(sku)
    end
    text    :name, :stored => true do
      SymmetricEncryption.decrypt(name)
    end
  end

  field :sku,   type: String
  field :name,  type: String

  belongs_to :webshop, :inverse_of => :products
end
```

I am currently indexing my `Product` objects like this:

``` ruby
Product.where(:updated_at.gte => 24.hours.ago).each do |product|
  product.solr_index!
end
```

I assume that for the `product.solr_index!` method to work some connection between Sunspot and Mongoid objects must be established by default. But this way, if you want to know the `name` and `sku`of a Mongoid object you can just look up the corresponding Sunspot object. How can I avoid this? In other words, how do I cut the direct connection between Mongoid and Sunspot objects, while still being able to re-index in some way?

P.s.

I imagine that I might be able to recognize Sunspot/Mongoid pairs in the same way that I do when searching:

``` ruby
#1) Perform the search
search_query = Sunspot.search(Product) do
  fulltext(params[:query]) do
    fields :name, :remote_id
  end
  with(:webshop_id, params[:webshop_id])
  paginate(:page => 1, :per_page => 100)
  order_by(:score, :desc)
end

#2) Encrypt the remote_id and find the Mongoid object that has a matching encrypted `sku`
items = search_query.hits.each do |hit|
    bson_id = Product.where(sku: SymmetricEncryption.encrypt(hit.stored(:remote_id).first), webshop_id: params[:webshop_id]).first._id
end
```

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
