### ISSUE TITLE
LoadError: cannot load such file -- tasks/emoji.rake

### ISSUE THREAD

**Issue by poombavai** [sunspot/sunspot#815]
Hello.. Could not start sunspot. 

    forum$ bundle exec rake sunspot:solr:start
    rake aborted!
    LoadError: cannot load such file -- tasks/emoji.rake

How to solve this?

**Comment by bragboy** [comment]
it seems the problem is with your file `tasks/emoji.rake` and has nothing to do with sunspot. Fix that error..
