### ISSUE TITLE
[BUG] Atomic update erases all stored fields

### ISSUE THREAD

**Issue by serggl** [sunspot/sunspot#825]
Just found a bug in `atomic_update` function. Instead of updating a single stored value (as it suppose to do), it could clear ALL the stored fields for the search document. 

Here is the model and its `searchable` definition: 
```ruby
class Installation
  searchable auto_index: true, auto_remove: true do
    string(:customer_name, stored: true)
    string(:customer_mobile, stored: true)
    string(:installation_tags, multiple: true, stored: true) 
    boolean(:active_now, stored: true)
  end
end
```

After indexing, Solr document will look like this:
```json
{
"responseHeader":{
  "status":0,
  "QTime":0,
  "params":{
    "q":"*:*",
    "indent":"on",
    "fq":"id:\"Installation 166039\"",
    "wt":"json"
  }
},
"response":{"numFound":1,"start":0,"docs":[
{
  "id":"Installation 166039",
  "customer_name_ss":"ew qw",
  "customer_mobile_ss":"255761222888",
  "installation_tags_sms":["tag"],
  "active_now_bs":false,
  "_version_":"1550444698702708736"}]
}}
```

Calling `Installation.find(166039).atomic_update(installation_tags: [])` will clear the document:
```json
{
"responseHeader":{
  "status":0,
  "QTime":0,
  "params":{
    "q":"*:*",
    "indent":"on",
    "fq":"id:\"Installation 166039\"",
    "wt":"json"
  }
},
"response":{"numFound":1,"start":0,"docs":[
{
  "id":"Installation 166039",
  "_version_":"1550452991644925952"}]
}}
```

**Comment by serggl** [comment]
moreover, setting any field value to `nil` via `atomic_update` will cause the same result...

**Comment by serggl** [comment]
@bragboy In the 1-10 scale, I would give this a 9.
Happy to answer any questions in a linked pR

**Comment by serggl** [comment]
any chance the fix for this will be merged?

**Comment by dilkhush** [comment]
@serggl 

I am facing this and other issues also 
Please see this gist
https://gist.github.com/dilkhush/cc7e5b8adea0bf7f043787922de1336c

**Comment by serggl** [comment]
@dilkhush try downgrading `rsolr` to `1.1.2`

**Comment by dilkhush** [comment]
@serggl Which sunpot version is using atomic_update with rsolr '1.1.2' verison because I am using sunspot 2.2.7 so its having the latest one rsolr '2.1.0'

**Comment by serggl** [comment]
@dilkhush here's what in my  Gemfile.lock:
```
    rsolr (1.1.2)
      builder (>= 2.1.2)
    sunspot (2.2.7)
      pr_geohash (~> 1.0)
      rsolr (>= 1.1.1, < 3)
```

**Comment by dilkhush** [comment]
Thanks @serggl, Its working fine with the rsolr-1.1.2

But my current rsolr version is 2.1.0 So downgrading my gem version to 1.1.2 will not break any of my other changes, How can i ensure this ?

**Comment by serggl** [comment]
@dilkhush this configuration works fine for me on heavily used production app for almost 2 years. It should work unless you have something specific in your app

**Comment by serggl** [comment]
🎉 related PR was just merged
