### ISSUE TITLE
hostname not being passed to rsolr

### ISSUE THREAD

**Issue by mwlang** [sunspot/sunspot#829]
When using Ruby 2.3, hostname from the sunspot.yml file isn't passed to the rsolr client.  That is, the url remains "localhost" even when changed in sunspot.yml

My guess is variable scoping issues as the following resolved my issue:
~~~ruby
module Sunspot
  module Rails
    class Configuration
      def hostname
        return @hostname if defined?(@hostname)
        @hostname   = solr_url.host if solr_url
        @hostname ||= user_configuration_from_key('solr', 'hostname')
        @hostname ||= default_hostname
      end
    end
  end
end
~~~

The above was originally:
~~~ruby
module Sunspot
  module Rails
    class Configuration
      def hostname
        unless defined?(@hostname)
          @hostname   = solr_url.host if solr_url
          @hostname ||= user_configuration_from_key('solr', 'hostname')
          @hostname ||= default_hostname
        end
        @hostname
      end
    end
  end
end
~~~
I noticed the original "unless defined?" pattern repeated for most other settings (port, scheme, userinfo, etc.), however did not test further than getting hostname working for my use-case.

**Comment by mlh758** [comment]
I haven't seen any such issue with the sunspot.yml file not actually providing configuration.

I'm going to close this due to age but will reopen if there is still a problem.
