### ISSUE TITLE
How to ignore fields from being indexed?

### ISSUE THREAD

**Issue by ismail44** [sunspot/sunspot#831]
Is it possible to ignore certain fields from being indexed? Currently, when I call .index on a field (because I have turned off auto_index), it is trying to index all the properties... including the ones provided from ActiveRecord::Base (i.e. type, class_name). Is there a way to only include the specific fields I want?

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
