### ISSUE TITLE
rake sunspot:solr:restart doesn't start Solr back up on Linux

### ISSUE THREAD

**Issue by phebal** [sunspot/sunspot#833]
Solr server exits but doesn't start back up. Problem is in `Sunspot::Solr::Server#exec_in_solr_executable_directory`. It does `exec(*command)`. That terminates the task when the script it calls terminates. Simple fix would be to do something like this:
```ruby
fork { exec(*command) }
Process.wait
```
in `exec_in_solr_executable_directory`

**Comment by vakuum** [comment]
This should be fixed with pull request #843.

**Comment by vakuum** [comment]
@phebal: The pull request #843 was merged! :tada:

@bragboy: This issue can be closed now.

**Comment by bragboy** [comment]
Thanks @vakuum
