### ISSUE TITLE
Ordering between groups (not within)

### ISSUE THREAD

**Issue by abrambailey** [sunspot/sunspot#840]
Let's say we have a set of groups of objects, with each object having a distinct score. Is there a way to find the average score for the group of objects and sort the groups based on these average scores?

**Comment by ethirajsrinivasan** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by abrambailey** [comment]
Does Sunspot support this functionality?

**Comment by abrambailey** [comment]
This is the best I could do for now:

`@branches.group(:business_name).groups.sort_by { |a| [-(a.solr_docs.map{|docs| docs["review_count_is"]}.sum), a.value] }.each do |group|`
