### ISSUE TITLE
RSolr::Error::Http - 404 Not Found Error: Not Found URI: http://localhost:8982/solr/default/select?wt=ruby Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"} 

### ISSUE THREAD

**Issue by bacancy** [sunspot/sunspot#844]
I'm new to the searching tool.

Do we need to install any external ubuntu library for sunspot solr??
If yes then which library I need To install?

If no, then Please help me to solve this error
```
RSolr::Error::Http - 404 Not Found Error: Not Found URI: http://localhost:8982/solr/default/select?wt=ruby Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"} Request Data: "fq=type%3AUser&fq=visible_b%3Atrue&sort=id_sort_i+desc&start=0&rows=20&q=*%3A*"
```

**Comment by bacancy** [comment]
Now I'm getting the error given below after reindexing.


```Solr::Error::Http - 400 Bad Request Error: 'undefined field username_fulltext','code'=>400}} URI: http://localhost:8982/solr/default/select?wt=ruby Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"} Request Data: "fq=type%3AUser&fq=visible_b%3Atrue&fq=username_fulltext%3Aabc&sort=id_sort_i+desc&start=0&rows=20&q=*%3A*"```

**Comment by jablkopp** [comment]
@bacancy can you tell me how did you fix the problem?

**Comment by mlh758** [comment]
The second issue should be fixable by reindexing the model.

**Comment by yarhtut** [comment]
I have same issue after change my config and fixed.
 `config/sunspot.yml` 
from
```
development:
  solr:
    hostname: localhost
    port: 8982
    path: /solr
    log_level: INFO
``` 
to
`
path: /solr/development
`

**Comment by ashish92skumar** [comment]
I am also having `RSolr::Error::Http - 404 Not Found Error` issue when trying to save or reindex the solr

**Comment by rahuldwivedi** [comment]
I am also having the same issue please have a look on my error log

`Traceback (most recent call last):`
        `1: from (irb):3`
`RSolr::Error::Http (RSolr::Error::Http - 404 Not Found)`
`Error:     Not Found`

`URI: http://localhost:8982/solr/development/update/extract wt=ruby&literal.id=User+5&literal.type=User&literal.type=ApplicationRecord&literal.type=ActiveRecord%3A%3ABase&literal.class_name=User&literal.id_i=5&literal.created_at_d=2018-07-10T10%3A41%3A01Z&literal.updated_at_d=2018-07-10T10%3A41%3A01Z&fmap.content=document_attachment_attachment
Request Headers: {"Content-Type"=>""}
Request Data: ""`

`Backtrace: /home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'`
/`home/rails/.rvm/gems/ruby-2.5.1@solr-full/bundler/gems/sunspot-47783f9f10e3/sunspot_rails/lib/sunspot/rails/solr_instrumentation.rb:16:in `block in send_and_receive_with_as_instrumentation'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/bundler/gems/sunspot-47783f9f10e3/sunspot_rails/lib/sunspot/rails/solr_instrumentation.rb:15:in `send_and_receive_with_as_instrumentation'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/bundler/gems/sunspot_cell-749b3ea059c3/lib/sunspot/rich_document.rb:40:in `add'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/bundler/gems/sunspot_cell-749b3ea059c3/lib/sunspot_cell/indexer.rb:25:in `block in add_documents'`
`/home/rails/.rvm/gems/ruby-2.5.1@solr-full/bundler/gems/sunspot_cell-749b3ea059c3/lib/sunspot_cell/indexer.rb:24:in `each'`
