### ISSUE TITLE
Order by using a parameter

### ISSUE THREAD

**Issue by amitej1** [sunspot/sunspot#845]
I want to order the result set of a Model using a custom parameter based on the current user's id. 
I haven't been able to find any way to do this. Is there any way a custom parameter can be passed using the order by syntax?

**Comment by bjacobs09** [comment]
I have the same issue. I want the user be able to change the order_by. How can I pass in a parameter to sort by?
Ex: order_by(@sort_by, @sort_type)

**Comment by lalit-nga** [comment]
Please take a look an example below.

```
def sort_by_options
    (options ||= []) << ["Rating", "average_rating-desc"]
    options << ["Newest", "updated_at-desc"]
    options << ["Low Price", "price-asc"]
    options << ["High Price", "price-desc"]
    options << ["Views", "views-desc"]
    options
  end
```

Here sort_by obtain from `params` object.

```
order_by_text = (sort_by || "average_rating-desc").split("-").map { |e| e.to_sym }
order_by(order_by_text.first, order_by_text.last)
```

Hope this will help :)
