### ISSUE TITLE
Sunspot solr fails to actually start solr

### ISSUE THREAD

**Issue by Sankarshan-Mudkavi** [sunspot/sunspot#849]
I'm on RHEL 7 instance and ```bundle exec rake sunspot:solr:start``` prints Successfully started Solr, however it fails to actually launch solr (cannot connect to solr admin and restarting brings up a no process error).

However when I try to run ```bundle exec rake sunspot:solr:run```, it prints out: ```This script requires extracting a WAR file with either the jar or unzip utility, please install these utilities or contact your administrator for assistance.```

I've been unable to actually start a solr instance with any details on the wiki

**Comment by lalit-nga** [comment]
Hi, Have you installed the Java on your instance?

**Comment by victorsosa** [comment]
@Sankarshan-Mudkavi please delete or backup the 'sorl' directory and do `bundle exec rake sunspot:solr:stop` and `bundle exec rake sunspot:solr:start`; that should fix the config issues (due to upgrade the solr.xml config file is not compatible after 2.2.2 sunspot_solr version )

**Comment by mlh758** [comment]
Is SOLR actually installed on your RHEL instance?

**Comment by kvkashyap29** [comment]
rake sunspot:solr:run --trace
** Invoke sunspot:solr:run (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute sunspot:solr:run

i am trying to use the run command and this is all it does after which the command execution stops can someone help me

**Comment by mlh758** [comment]
@kvkashyap29 It would be better to open a new issue than jumping onto an unrelated one.

Closing this since there was no response from the original requestor and it's gone stale.
