### ISSUE TITLE
Impossible to get multiple occurrences per searchable post/document

### ISSUE THREAD

**Issue by charltonh** [sunspot/sunspot#850]
It seems like searches are limited to one occurrence per post/document in the results.  Looks like the way sunspot was designed is to return on first occurrence of the search parameter(s) inside the searchable post (or document), and not able to get multiple occurrences back in the results/hits structures.  I'm not sure but the term "hits" in the documentation does not appear to refer to occurrences of the search term inside the document, nor am I seeing additional occurrences coming back inside hits vs results.

I have a project that was written with solr/sunspot but needs to return the actual occurrence count, not the document count which has the occurrence.  The fact that this does not look possible despite such a well-crafted elaborate search library tool, is IMO a necessary feature.  So I opened a bug here.  My apologies if I have overlooked something (if I have it's not documented anywhere I could find).

**Comment by mlh758** [comment]
The hits structure is more like the raw Solr search results [documentation here](https://github.com/sunspot/sunspot#hits-vs-results). You can store additional information in Solr and retrieve it on the hit without having to query your database via the hit object. If you use the results object the gem actually loads the records from your database.

[Highlighting](https://github.com/sunspot/sunspot#highlighting) is how you would see what actually matched on a hit.
