### ISSUE TITLE
Possible issue with joins on Rails 5

### ISSUE THREAD

**Issue by danham-slalom** [sunspot/sunspot#869]
I am not getting any results back on join I have in my `searchable` method.  My `searchable` method from the `Event` model looks like this:
```     
searchable do
    text :title, :default_boost => 2`
    text :segment
    join(:name, :target => Department, :type => :text, :join => { :from => :department_id, :to => :id })
end
```

And the `searchable` method I included in the `Department` model looks like this:
```
searchable do 
  text :name
end
```

When I do an `Event.search { fulltext: '<department name here>' } `, I expect for any `Event` that has a related `Department` with `name` that matches my search parameter to be returned.  Am I understanding this functionality correctly?  Is there something I'm missing in how I'm implementing this?

I wondered if this might be an issue with sunspot on Rails 5, since I haven't been able to find very much guidance specifically related to using sunspot on Rails 5. 

I am running sunspot 2.2.7 and rsolr 2.0.2.

**Comment by mlh758** [comment]
When I was setting up my joins I had to add the ids that would be joined in both models so Department would need `integer id` and Event would need `integer department_id` for it to know about the fields to connect on.

**Comment by danham-slalom** [comment]
@mlh758 do you mean add the ids as class variables in the models as opposed to just having them declared in the schema?

**Comment by mlh758** [comment]
No I mean add those attributes to the searchable block so they get indexed

**Comment by danham-slalom** [comment]
@mlh758 I'm getting an error including the attribute `integer :id` in the `searchable` method on `Department`. 

Here is is the error:
`RSolr::Error::Http: RSolr::Error::Http - 400 Bad Request
Error: {"responseHeader":{"status":400,"QTime":1},"error":{"msg":"Exception writing document id Department 1 to the index; possible analysis error.","code":400}}`

Since `id` is of type `Fixnum`, is there a more appropriate index type to use than `integer`?

**Comment by mlh758** [comment]
That error isn't enough for me to know immediately what went wrong for you. [Fixnum](https://ruby-doc.org/core-2.2.0/Fixnum.html) is a type of integer in Ruby so that still seems appropriate. SOLR will be storing it in its own data format anyway since it isn't actually connected to your RDBMS.

In any case, you'll need to index the two ID columns in the searchable block for the joins to work: https://github.com/sunspot/sunspot#joins
