### ISSUE TITLE
i'm not getting perfet result with solr

### ISSUE THREAD

**Issue by MajedBojan** [sunspot/sunspot#870]
Hello Guys
i'm working in solr search in rails
i'm getting those units has all the array of amenities those i'm passing
if i use any_of it will display all the units those has even one key from the array but i want only those units have all the array am passing
this my code

  with(:amenities).any_of([params[:amenities]]) if params[:amenities].present?
i changed to

with(:amenities).all_of([params[:amenities]]) if params[:amenities].present?
but it's giving same result

**Comment by mlh758** [comment]
If you do a query like:
```
Model.search do
  all_of do
    with(:amenities, params[:amenities])
  end
end
```

You'll see a the query generate something like this:
`<Sunspot::Search:{:fq=>["type:Model", "amenity_im:(10092 OR 10095 OR 1120)"], :start=>0, :rows=>30, :q=>"*:*"}>`

You can see that it is asking for any matched ID using `OR`.

However, if you alter the query like this:
```
s = Page.search do
  all_of do
    params[:amenities].each do |id|
      with(:amenities, id)
    end
  end
end
```

Gives you a query like:
`<Sunspot::Search:{:fq=>["type:Page", "amenity_im:10092", "amenity_im:10095", "amenity_im:1120"], :start=>0, :rows=>30, :q=>"*:*"}>`
