### ISSUE TITLE
Solr 6 and Sunspot Roadmap

### ISSUE THREAD

**Issue by jitensachdeva** [sunspot/sunspot#871]
Hi I was just trying to scan through the sunspot documentation and no where it is mentioned that it was tested with Solr 6 and above.

Is there any plan to keep sunspot catching with latest releases ?

**Comment by ezraball** [comment]
I'm also curious about this.

**Comment by sriramg** [comment]
Any update on this?   We use this in production and it looks like Solr 6.x is the oldest release that has LTS (http://lucene.apache.org/solr/community.html).  Anyone tried sunspot 2.2.7 with solr 6 or solr 7?

**Comment by serggl** [comment]
we are running Solr 6 on our production system for a while already. No issues found
