### ISSUE TITLE
Unrecognized VM option 'PrintHeapAtGC'

### ISSUE THREAD

**Issue by psantos10** [sunspot/sunspot#872]
It seems like Java 9 is not supported yet 

## Command:

>  bin/rails sunspot:solr:run

Result:

> 
> Starting Solr on port 8982 from /Users/psantos/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sunspot_solr-2.2.7/solr/server
> 
> Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
> Java HotSpot(TM) 64-Bit Server VM warning: Option UseParNewGC was deprecated in version 9.0 and will likely be removed in a future release.
> Unrecognized VM option 'PrintHeapAtGC'
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

**Comment by groe** [comment]
Having the same problem with sunspot 2.2.7 and Java 9.

With sunspot 2.1.1 it works though.

**Comment by danielgbaena** [comment]
Same problem here

**Comment by guantong** [comment]
same problem with sunspot 2.2.7 and java 9

**Comment by vikrambahl** [comment]
Any timelines by when this is expected to be resolved?

**Comment by groe** [comment]
If you don't need GC logging, #883 fixes this. Hope the PR is merged soon, otherwise feel free to use `gem 'sunspot_solr', git: 'https://github.com/groe/sunspot.git', branch: 'java9compat'` in your Gemfile.

**Comment by groe** [comment]
Quick follow up if anyone else is trying this: I had some more issues with java 9 and gave that up for now. Also, the bundled solr version is out of date anyway, so I went with a [docker container for solr](https://hub.docker.com/_/solr/).

**Comment by serggl** [comment]
I also highly recommend to use `sunspot_solr` gem only for testing purposes. I you run Solr in your production environment - then standalone setup or even docker is much better choice since its much more configurable
