### ISSUE TITLE
Get raw query url

### ISSUE THREAD

**Issue by 23tux** [sunspot/sunspot#875]
Hi,

I often have the problem that I want to debug a query, and I'd like to see the raw query that is sent to Solr. Is there a way to get the actual raw query URL from sunspot?

**Comment by maxpollack** [comment]
This is very late, but if you are looking in your logs you should be able to see the requests that are sent out. It's not the exact URL, but you will see all the parameters it is constructed from:

```SOLR Request (23.0ms)  [ path=select parameters={fq: ["type:AType", "lat_es:[* TO *]", "lon_es:[* TO *]", "_query_:"{!geofilt sfield=location_locm pt=39.978162,-75.12565 d=160.9344}""], start: 0, rows: 10000, stats: true, stats.field: ["est_impressions_is"], q: "*:*"} ]```
