### ISSUE TITLE
how to  config "sunspot join and group" in rails

### ISSUE THREAD

**Issue by 4268146** [sunspot/sunspot#885]
# I have a query question about join :

### Code Of Model File 
```
class TrackPost < ApplicationRecord
searchable(:auto_index => true, :auto_remove => true) do
    integer :id
    integer :a_id
    integer :post_id
    integer :b_id
    integer :c_type
    boolean :state
  end

end

class Post < ApplicationRecord
...
  searchable(:auto_index => true, :auto_remove => true) do
    integer :id
    string(:id_str) { |p| p.id.to_s }
    join(:a_id, :target => TrackPost, :type => :integer, :join => { :from => :post_id, :to => :id })
    join(:b_id, :target => TrackPost, :type => :integer, :join => { :from => :post_id, :to => :id })
    join(:c_type, :target => TrackPost, :type => :integer, :join => { :from => :post_id, :to => :id })
  end
...
end
```

### Code Of Controller File About Search
```
    search = Post.search do
        with(:a_id, [1,2,3,4])
        with(:b_id, [1,2])
        with(:c_type, [2])
        group(:id_str)
    end
```

### result about search list, which not's  my datas

```data list
[
{id: 1, a_id: 1, b_id: 1, c_type: 2},
{id: 2, a_id: 1, b_id: 1, c_type: 1},
{id: 3, a_id: 1, b_id: 1, c_type: 2},
]

```
data has "c_type = 1", how to config ：

```

[ path=select parameters={
  fq: [
    "type:Post", "{!join from=post_id_i to=id_i}c_type_i:(2)", 
    "{!join from=post_id_i to=id_i}a_id_i:(1 OR 2 OR 3 OR 4)", 
    "b_id_i:(0)","
  ], 
  start: 0,
   rows: 130, 
  group: "true", 
  group.ngroups: "true", 
  group.field: ["id_str_s"], 
  q: "*:*"} ]


how to change query

from:

 fq: ["type:Post", "{!join from=post_id_i to=id_i}a_id_i:(1 OR 2 OR 3 OR 4)", "{!join from=post_id_i to=id_i}c_type_i:(2)"

to:

fq: ["type:Post", "{!join from=post_id_i to=id_i}a_id_i:(1 OR 2 OR 3 OR 4) and c_type_i:(2)"


```

**Comment by mlh758** [comment]
It looks like your model config is a little off. To get join working in my application I had to index the ids it would be joining to within the model. For example:

```
class JoinedTo < ApplicationRecord
...
searchable do
  integer :id
  text :content
end

class Joining < ApplicationRecord
  has_many :joined_to
...
searchable do
  integer joined_to_ids, multiple: true do
    joined_to.pluck(:id)
  end
  join(:content, target: JoinedTo, type: :text, join: { from: :id, to: :joined_to_ids })
end
```

**Comment by 4268146** [comment]
thanks, I will try your demo. Now I use ':store => true' in join , which merge two tables to a table .

**Comment by gr8bit** [comment]
@mlh758 I'm currently investigating the same issue as in the original post, or at least a fraction thereof: how to do a search with a condition that merges multiple join condition into one {!join ...} condition.

I have a Contract and a ContractPartner model:
```ruby
class Contract < ApplicationRecord
  has_many :contract_partners

  searchable do
    string :contract_number
    join(:broker_id, target: ContractPartner, type: :integer, join: { from: :id, to: :contract_id })
    join(:active_in_period, target: ContractPartner, type: :date_range, join: { from: :id, to: :contract_id })
  end
end

class ContractPartner < ApplicationRecord
  belongs_to :contract

  searchable do
    integer :broker_id
    date_range :active_in_period
  end
end
```

Now, if I search like this:
```ruby
Contract.search do
  all_of do
    with :broker_id, 43
    with(:active_in_period).containing(DateTime.now)
  end
end
```

the generated search searches for:
> all Contract models that have ContractPartner models which have a broker_id of 43 and that have ContractPartner models which are currently (DateTime.now) active. BUT these ContractPartner models may not be the same.

What I want, however, is:
> all Contract models that have ContractPartner models which have a broker_id of 43 and which are currently active.

So I want these two conditions combined into one {!join ...} instead of two separate joins (one for broker_id, one for active_in_period).

Can you please help?

**Comment by mlh758** [comment]
Could you provide the generated Solr query? Sunspot should be spitting it out in your console. Might help with debugging. I ended up no longer using `join` features because I needed information from the joined model as well and it was easier to store it in one place.

**Comment by gr8bit** [comment]
That was dummy code unfortunately, but here is the real search:
```
<Sunspot::Search:{:fq=>["type:PolicySummary", "{!join from=policy_id_is to=policy_id_i v='type:\"PolicyPartner\" AND _query_:\"{!field f=active_search_dr op=Intersects}2020-11-18T12:03:03Z\"'}", "{!join from=policy_id_is to=policy_id_i v='type:\"PolicyPartner\" AND broker_id_is:\"4\"'}"], :start=>0, :rows=>30, :q=>"*:*"}> 
```
or, broken down:
```
{
  :fq=>[
    "type:PolicySummary",
    "{!join from=policy_id_is to=policy_id_i v='type:\"PolicyPartner\" AND _query_:\"{!field f=active_search_dr op=Intersects}2020-11-18T12:03:03Z\"'}",
    "{!join from=policy_id_is to=policy_id_i v='type:\"PolicyPartner\" AND broker_id_is:\"4\"'}"
  ],
  :start=>0,
  :rows=>30,
  :q=>"*:*"
}
```
As you can see it joins twice when I'd rather have both conditions combined like this:
```
"{!join from=policy_id_is to=policy_id_i v='type:\"PolicyPartner\" AND _query_:\"{!field f=active_search_dr op=Intersects}2020-11-18T12:03:03Z\" AND broker_id_is:\"4\"'}"
```

**Comment by mlh758** [comment]
I have:

```xml
<str name="q.op">AND</str>
```

set in my defaults for the /select endpoints so... possibly dumb quesiton... what happens if you change your query to:

```rb
Contract.search do
    with :broker_id, 43
    with(:active_in_period).containing(DateTime.now)
end
```

**Comment by gr8bit** [comment]
I have q.op set to AND, too. Changing the search as you suggested doesn't change anything, there are still 2 joins being generated, one for each condition.

**Comment by mlh758** [comment]
Hm, given that I haven't used this functionality much, my only other thought would be to use `adjust_solr_params` in the search block to just add your broker_id_is query to the end of the existing query.

**Comment by gr8bit** [comment]
Good hint, will look into it, thanks! I didn't find much in the Sunspot code hinting possibilities to fine-tune joins...

**Comment by mlh758** [comment]
Your problem is likely that broker_id has to be obtained through a join as well so it's just always going to execute that. If you wanted to do it on the DSL you could move that to be indexed directly on your contract model if that's an option for you.

**Comment by gr8bit** [comment]
It would be an option, but how can I? Every ContractPartner has a date range and a broker id which need to be queried _together_. How could I move that querying to the Contract model?

Simple example, for one Contract,
> ContractPartner from 2019-01-01 until 2019-12-31 was broker id 23.
> ContractPartner from 2020-01-01 until 2020-12-31 was broker id 42.

And now I want to find all contracts from broker id 42 which were active in 2019.

**Comment by mlh758** [comment]
I was imagining something like

```rb
class Contract < ApplicationRecord
  has_many :contract_partners

  searchable do
    string :contract_number
    integer :broker_ids, multiple: true do
       contract_partners.pluck(:broker_id)
    end
    join(:active_in_period, target: ContractPartner, type: :date_range, join: { from: :id, to: :contract_id })
  end
end
```

Then your all_of or just multiple with statements wouldn't both require a join to get the values. I'm thinking Sunspot would know how to combine them appropriately that way.

**Comment by gr8bit** [comment]
Unfortunately, it doesn't (and it cannot either, but I'll get to that later). If I queried broker_ids as in your last example, the problem would remain: the query would fetch all contracts which have the desired broker_id in the contracts but also an active ContractPartner (which does NOT need to be connected to the broker). So for my "simple example" above, it would return the Contract, although it doesn't have a ContractPartner with broker_id 42 that was active in 2019. But I want to fetch only Contracts with at least ContractPartner that has the desired broker_id AND was active in the desired period.

As for joins, Sunspot cannot know if I would like to fetch:
* all Contracts which have a ContractPartner with broker_id AND (possibly another) ContractPartner that was active in the desired period or
* all Contracts which have a ContractPartner with broker_id AND that was active in the desired period.

The first one requires 2 separate joins with 1 condition each, the second one requires 1 join with 2 conditions. Sunspot cannot know which one I mean.
