### ISSUE TITLE
Clarification on Threading

### ISSUE THREAD

**Issue by mlh758** [sunspot/sunspot#903]
I have an application running Sidekiq with solr which brought me to the docs here: https://github.com/sunspot/sunspot#threading

It clearly indicates that I need to use the `ThreadLocalSessionProxy` class. I assumed that meant in an initializer so I added
`Sunspot.session = Sunspot::SessionProxy::ThreadLocalSessionProxy.new` to a `sunspot.rb` file.

This seems to not load my config however, either in the main thread or in any sidekiq threads. The next line indicates that I should be doing:
```
session = Sunspot::Rails.build_session  Sunspot::Rails::Configuration.new
Sunspot.session = session
```

but this is contradictory to the recommendation above. If you're on Rails do you use the build_session method in each thread instead of using `ThreadLocalSessionProxy`? Or is there a way to feed the config to `ThreadLocalSessionProxy` to avoid the first issue? I see that it builds a default config if not given one, but it errors if given `Sunspot::Rails::Configuration.new`.

Also, if I just call `Sunspot.commit` after each sidekiq job as middleware then I don't have any issues anyway. However, I'm worried about this solution because the docs say the default session is not thread safe so I assume this will bite me later.

If you can clarify what the docs intend, I'll happily open a PR updating the documentation after I test it out.

**Comment by mlh758** [comment]
Never mind on that `Sunspot.commit` thing. Would be nice to learn how to use `ThreadLocalSessionProxy`.

**Comment by tquill** [comment]
I'd like this clarified too.
- What would be the issues in indexing jobs in sidekiq using `Sunspot.index` without `ThreadLocalSessionProxy`?
- How do I setup `ThreadLocalSessionProxy` in rails using sidekiq?

**Comment by serggl** [comment]
```
$ rails c
Loading development environment (Rails 5.2.1)
[1] pry(main)> Sunspot.session.class
=> Sunspot::SessionProxy::ThreadLocalSessionProxy
```

this is the default session setup. No additional actions are required to index data in threads (sidekiq)

**Comment by mlh758** [comment]
What ended up resolving my issue is enabling auto soft commit in my schema. It wasn't that the gem was failing to keep things in sync it was that we weren't committing changes to the search index often enough.
