### ISSUE TITLE
Include JTS in sunspot_solr?

### ISSUE THREAD

**Issue by maxpollack** [sunspot/sunspot#905]
My understanding is that JTS is not included in Solr by default because of licensing issues - would this keep you from rolling JTS into `sunspot_solr` for the purposes of local development? Most solr providers out there include JTS in their offerings for things like geospatial indexes using the `SpatialRecursivePrefixTreeFieldType`, and it actually doesn't take a huge amount of munging `schema.xml` to support it in sunspot. Because we rely on `sunspot_solr` for our local development, we had to fork the entire sunspot repo just to include the JTS jar in Solr's `bin` directory.

Is there a reason that `sunspot_solr` is opting to not include this dependency, or is it just that it hasn't been asked for yet? I suspect it would be valuable to other users to have the functionality baked in, and could open a PR if you'd like.

**Comment by mlh758** [comment]
I'm going to close this since I'd rather remove the bundled Solr entirely and let people set it up as they please with a Docker image or other local setup.
