### ISSUE TITLE
I am having trouble with any results showing in my results page.

### ISSUE THREAD

**Issue by gracesaint** [sunspot/sunspot#906]
Heres the searchable code in my product.rb file:

searchable do
      text :title, :description, :size, :color
       
  end
  

and heres the code in my results.html.erb file:
<% if !@res || @res.total == 0 %>
     <span>No results.</span>
     <% else %>
     <span>Found <%= "#{@res.total}" %> results.</span>
     <table>
<thead> <tr>
           <th>Name</th>
           <th>Description</th>
           <th>Price</th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% @res.results.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.description %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
<% end %>

**Comment by serggl** [comment]
I bet you miss `auto_index: true` in your searchable configuration

**Comment by mlh758** [comment]
Closed due to inactivity.
