### ISSUE TITLE
Unrecognized VM option 'UseParNewGC'

### ISSUE THREAD

**Issue by igorb** [sunspot/sunspot#907]
➜  rake sunspot:solr:run

Starting Solr on port 8982 from /Users/igorbilan/.rvm/gems/ruby-2.2.4/gems/sunspot_solr-2.3.0/solr/server

Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

 java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

**Comment by serggl** [comment]
@igorb do you want to be a volunteer and fix bash scripts fo exclude this deprecated ENV value? https://github.com/sunspot/sunspot/search?utf8=✓&q=GC_TUNE

**Comment by brutuscat** [comment]
@serggl yes please do!

**Comment by alexandrubeu** [comment]
Any updates on this thread? I just installed ubuntu 19.04 and unfortunately I can not install `java8` which means that I can not use this package. Can you please update?
