### ISSUE TITLE
Possible to search with short words, or words containing numbers?

### ISSUE THREAD

**Issue by hakunin** [sunspot/sunspot#908]
I've got an item that says "4k display" and when I search for "4k display" that item does not seem to be prioritized and other items with "display" (without 4k) come up.

Is the "4k" bit removed by design? How can approach this issue?

**Comment by mlh758** [comment]
That will depend a lot on how you have defined your schema and is more in the purview of solr itself.

Check out the [filter](https://lucene.apache.org/solr/guide/6_6/filter-descriptions.html) documentation. I've run into this issue before when the minimum gram size was too small.
