### ISSUE TITLE
sunspot_rails time sending with d instead dt suffix

### ISSUE THREAD

**Issue by ericnordelo** [sunspot/sunspot#912]
This cause errors like:

Error adding field 'created_at_d'='2018-07-30T19:55:18Z' msg=For input string: \"2018-07-30T19:55:18Z\""

while the core of solr is expecting created_at_dt or similar pdate type

**Comment by serggl** [comment]
well, this question is not for the github issue, more a stackoverflow question.
You need to configure your search field as `time(:created_at, trie: true)`
