### ISSUE TITLE
Sunspot::Solr using gem yields different (incorrect) results than when using system installation

### ISSUE THREAD

**Issue by gs2589** [sunspot/sunspot#914]
When keeping the database constant, the results to a query with the sunspot_solr gem installation are different than when I install Solr in the system directly. Using the gem, the results don't always make sense.

I'm not sure what additional information to provide to help troubleshoot, because there are not errors.

If anyone can advise how I can troubleshoot this and what additional data I can provide so that people can help me.

Thanks!

**Comment by serggl** [comment]
It all depends on schema config sets. Try comparing them

**Comment by mlh758** [comment]
Closing this for now, it seems likely to be a setup issue. If it is still a problem comment back and I'll try to help you figure it out.
