### ISSUE TITLE
RSolr::Error::Http: RSolr::Error::Http - 401 Unauthorized

### ISSUE THREAD

**Issue by balamundru** [sunspot/sunspot#925]
Error: 'RunExecutableListener is deprecated and disabled by default for security reasons. Legacy applications still using it must explicitely pass \'-Dsolr.enableRunExecutableListener=true\' to the Solr command line. Be aware that you should really disable API-based config editing at the same time, using \'-Ddisable.configEdit=true\'!','code'=>401}}

URI: http://localhost:8983/solr/staging/update?wt=ruby
Request Headers: {"Content-Type"=>"text/xml"}
Request Data
: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><commit softCommit=\"false\"/>"

**Comment by mlh758** [comment]
What version of solr and lucene are you using, and what version of the gem?

**Comment by santu-git** [comment]
I am facing same issue. I am using 
Solr 5.5.5.
lucene 5.5.5
Sunspot 2.3.0
With document indexing support.

**Comment by mlh758** [comment]
You should really update to a supported version: https://lucene.apache.org/solr/downloads.html#about-versions-and-support
