### ISSUE TITLE
Compatibility with non-EOL SOLR versions

### ISSUE THREAD

**Issue by cec** [sunspot/sunspot#951]
Hi all,

sunspot_solr currently bundles SOLR 5.3.x.

I've been using SOLR 5.5.5 (October 2017) on production running on Java 8 without issues.

According to SOLR [docs](https://lucene.apache.org/solr/downloads.html#about-versions-and-support), both SOLR 5 and SOLR 6 reached EOL (although 6.6.6 was released in April 2019).

Moreover SOLR 5.5.5 doesn't work out of the box on Java 11, which is the new LTS.

Does anyone have data about latest sunspot's compatibility with SOLR 6?

Does anyone have data about latest sunspot's compatibility with SOLR 7?

Thanks :)

**Comment by serggl** [comment]
I do confirm it works with Solr 6 / 7. 
In our company, we dont use `sunspot_solr` gem at all now  - production runs standalone version, developers use docker image

**Comment by cec** [comment]
Hi @serggl ,

thanks for the quick reply! 

I'm not using `sunspot_solr`, but the `schema.xml` generated by the [rake task](https://github.com/sunspot/sunspot/blob/master/sunspot/tasks/schema.rake) is copied from the `sunspot_solr` directory, so I guess I'm using a `schema.xml` that worked with 5.x, but may contain invalid/deprecated configurations for solr 6/7

In particular I'd like to know if you had to adjust the fields and dynamicFields used by Sunspot.

Thanks :)

**Comment by mlh758** [comment]
We are using Solr 7.7 now in production. Similar setup as @serggl with developers using docker and standalone deployed on a VM in production. We’ve been experimenting with a Zookeeper deployment on Kuberbetes and that has worked well too. 

When we upgraded we had to move our boosts to happen at search instead of during indexing. Trie fields are gone but we didn’t use those anyway.

**Comment by cec** [comment]
Hi @mlh758 

thanks for the information!

Regarding trie fields, it would then be a matter of replacing references to `solr.TrieTYPEField` with `solr.TYPEPointField` as stated in the [docs](https://lucene.apache.org/solr/guide/7_0/field-types-included-with-solr.html).

**Comment by mlh758** [comment]
I think I just removed them from our scheme since we didn’t use them.

**Comment by satish-zol** [comment]
> I do confirm it works with Solr 6 / 7.
> In our company, we dont use `sunspot_solr` gem at all now - production runs standalone version, developers use docker image

can you please explain how to use standalone with rails?

**Comment by mlh758** [comment]
Are you using the `sunspot_solr` gem in production right now?

Standalone would be deploying Apache Solr to a server/VM/container or whatever your infrastructure allows for and then pointing the solr config to that.

sunspot.yml might look something like:
```yaml
production
    hostname: <%= ENV['SOLR_HOSTNAME'] || 'localhost' %>
    port: 8983
    path: /solr/yourApp
```

**Comment by mlh758** [comment]
There is now an examples directory with a solr core that works on 7 that you could use as a baseline for your own work. It also lays out some more details and links for how you might [use this in production](https://github.com/sunspot/sunspot#running-solr-in-production-environment)

**Comment by cec** [comment]
Thanks @mlh758  I'll try this today
