### ISSUE TITLE
Composite ID does not support atomic_update and remove_by_id

### ISSUE THREAD

**Issue by shatalov-boris** [sunspot/sunspot#958]
related PR - #943

I'm not sure if it's the real issue or I just using the gem in wrong way.

So assume we have `User` class defined like this:
```ruby
class User < ApplicationRecord
  belongs_to :company

  searchable do
    id_prefix do
      "COMPANY#{company_id}!"
    end

    text :name, stored: true
  end
end
```
and have one user instance
```ruby
user = User.create!(name: "test", company_id: 2)
user # { id: 1, name: "test", company_id: 2 }
```
when we try to update it either on class level
```ruby 
User.atomic_update(user.id => { name: "new name" })
```
or instance level
```ruby
user.atomic_update(name: "new name")`
```
both cases will generate solr id  - `User 1`, not `COMPANY2!User 1`.

As I found, it related to this line - https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot/indexer.rb#L153
So `id` generates via `index_id_for` method (which know nothing about routing prefix)
```ruby
def index_id_for(class_name, id) #:nodoc:
  "#{class_name} #{id}"
end
```
not `index_id` method
```ruby
def index_id #:nodoc:
  setup     = Sunspot::Setup.for(@instance.class)
  id_prefix = setup ? setup.id_prefix_for(@instance) : nil

  InstanceAdapter.index_id_for("#{id_prefix}#{@instance.class.name}", id)
end
```

I understood that it can be hard or performance consuming to check `id_prefix` block for each item on `atomic_update`. Is there a workaround about it?

Currently I monkey-patched some methods to be able to pass full id directly:
```ruby
User.atomic_update( "COMPANY#{user.company_id}!User #{user.id}" => { name: "new name" })
```

Also, I'm happy to help with PR if it's something need to be fixed.

**Comment by serggl** [comment]
> I understood that it can be hard or performance consuming to check id_prefix block for each item on atomic_update. Is there a workaround about it?

I think this was just missed. 👍  for the PR

**Comment by shatalov-boris** [comment]
Finally, I'm back.

The thing is a bit more complicated than I thought initially.
The issue is also related to [remove_by_id](https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot.rb#L474) and [remove_by_id!](https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot.rb#L482) methods because they also use [index_id_for](https://github.com/sunspot/sunspot/blob/master/sunspot/lib/sunspot/adapters.rb#L79).

It's easy to fix this issue for `id_prefix` defined as string or symbol because we don't need instance object. The problem appears when we use block for `id_prefix`. 

Code inside the block is related to instance, but `remove_by_id` and `atomic_update` methods designed to be as simple as possible and work only with ids. They do not initialize instances.

I have several possible solutions:

1. Allow a developer to pass full solr id to `atomic_update` and `remove_by_id` methods instead of just instance's id.


Before:
```ruby
User.atomic_update(user.id => { name: "new name" })
Sunspot.remove_by_id(User, user.id)
```

After:
```ruby
User.atomic_update( "COMPANY#{user.company_id}!User #{user.id}" => { name: "new name" })
Sunspot.remove_by_id(User, "COMPANY#{user.company_id}!User #{user.id}")
```
`"COMPANY#{user.company_id}!User #{user.id}"` can be extracted to model method like `solr_id`:
```ruby
class User < ApplicationRecord
  belongs_to :company

  searchable do
    id_prefix { solr_id_prefix }

    text :name, stored: true
  end

  def solr_id
	"#{solr_id_prefix}User #{id}"
  end

  private
  
  def solr_id_prefix
    "COMPANY#{company_id}!"
  end
end
```

```ruby
User.atomic_update( user.solr_id => { name: "new name" })
Sunspot.remove_by_id(User, user.solr_id)
```

This solution is backward compatibility:
If `id_prefix` is defined on a model we will use the id provided by a developer directly. If there is no `id_prefix` we will keep current behavior with calling `index_id_for` method.


2. Allow to accept instance as a key for `atomic_update` and `remove_by_id` methods:

Before:
```ruby
User.atomic_update(user.id => { name: "new name" })
Sunspot.atomic_update(User, user.id => { name: "new name" })
Sunspot.remove_by_id(User, user.id)

```
After:
```ruby
User.atomic_update(user => { name: "new name" })
Sunspot.atomic_update(User, user => { name: "new name" })
Sunspot.remove_by_id(User, user)
```
This solution is also backward compatibility - we will use the new behavior only if an instance is provided. 
But it breaks the semantic of method names - `remove_by_id` method with instance as the argument. But we will be able to simple fetch required `id_prefix`.


3. Initialize instance inside `atomic_update` and `remove_by_id` methods.

We can initialize instance ourselves by provided ids. 
Something like this:
```ruby
  def atomic_update(clazz, updates = {}) 
    instances = clazz.where(id: updates.map { |id, _| id })
    ...
  end
```
But it can be tricky, as we do not know what primary key is used for a model. And also it can cause N+1 issue if `id_prefix` calls related models.

@serggl What do you think about all of this?

**Comment by serggl** [comment]
@shatalov-boris I would go with option 2 for atomic updates. As for `remove_by_id` - it is kinda low-level API, I assume just `remove` will fork for the composite id?

**Comment by shatalov-boris** [comment]
Ok, will do PR in few days
