### ISSUE TITLE
NoMethodError: undefined method `searchable'

### ISSUE THREAD

**Issue by Diyilou** [sunspot/sunspot#987]
I deply the env with document, but it throw a error: undefined method `searchable', how to fixed it ? help, best wish!

`class ArcArchives
  
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String, default: ''

  searchable do
    string :title
  end`

**Comment by mlh758** [comment]
Your class doesn't inherit from ActiveRecord::Base, which is where the `Searchable` function gets added to a class.

https://github.com/sunspot/sunspot/blob/master/sunspot_rails/lib/sunspot/rails/init.rb#L4

You'll probably need to manually configure objects for search if you are using Mongoid.
